# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `action_text-trix` gem.
# Please instead update this file by running `bin/tapioca gem action_text-trix`.


module Trix; end
class Trix::Engine < ::Rails::Engine; end

# pkg:gem/action_text-trix#lib/action_text/trix/version.rb:2
Trix::VERSION = T.let(T.unsafe(nil), String)
