# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `actionmailer` gem.
# Please instead update this file by running `bin/tapioca gem actionmailer`.


module ActionMailer
  extend ::ActiveSupport::Autoload

  class << self
    def deliver_all_later(*deliveries, **options); end
    def deliver_all_later!(*deliveries, **options); end
    def deprecator; end
    def eager_load!; end
    def gem_version; end
    def version; end

    private

    def _deliver_all_later(delivery_method, *deliveries, **options); end
  end
end

class ActionMailer::Base < ::AbstractController::Base
  include ::ActionMailer::Callbacks
  include ::ActiveSupport::Callbacks
  include ::ActionMailer::DeliveryMethods
  include ::ActionMailer::QueuedDelivery
  include ::ActiveSupport::Rescuable
  include ::ActionMailer::Rescuable
  include ::ActionMailer::Parameterized
  include ::ActionMailer::Previews
  include ::ActionMailer::FormBuilder
  include ::ActionView::ViewPaths
  include ::AbstractController::Rendering
  include ::AbstractController::Logger
  include ::ActiveSupport::Benchmarkable
  include ::AbstractController::Helpers
  include ::AbstractController::Translation
  include ::AbstractController::AssetPaths
  include ::AbstractController::Callbacks
  include ::AbstractController::Caching::Fragments
  include ::AbstractController::Caching::ConfigMethods
  include ::AbstractController::Caching
  include ::ActionView::Rendering
  include ::ActionView::Layouts
  extend ::ActionMailer::Callbacks::ClassMethods
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActionMailer::DeliveryMethods::ClassMethods
  extend ::ActiveSupport::Rescuable::ClassMethods
  extend ::ActionMailer::Rescuable::ClassMethods
  extend ::ActionMailer::Parameterized::ClassMethods
  extend ::ActionMailer::Previews::ClassMethods
  extend ::ActionMailer::FormBuilder::ClassMethods
  extend ::ActionView::ViewPaths::ClassMethods
  extend ::AbstractController::Helpers::Resolution
  extend ::AbstractController::Helpers::ClassMethods
  extend ::AbstractController::Callbacks::ClassMethods
  extend ::AbstractController::Caching::Fragments::ClassMethods
  extend ::AbstractController::Caching::ClassMethods
  extend ::AbstractController::Caching::ConfigMethods
  extend ::ActionView::Rendering::ClassMethods
  extend ::ActionView::Layouts::ClassMethods

  def initialize; end

  def __callbacks; end
  def _deliver_callbacks; end
  def _helper_methods; end
  def _helper_methods=(_arg0); end
  def _helper_methods?; end
  def _layout_conditions; end
  def _layout_conditions?; end
  def _process_action_callbacks; end
  def _run_deliver_callbacks; end
  def _run_deliver_callbacks!(&block); end
  def _run_process_action_callbacks; end
  def _run_process_action_callbacks!(&block); end
  def _view_cache_dependencies; end
  def _view_cache_dependencies=(_arg0); end
  def _view_cache_dependencies?; end
  def asset_host(*_arg0, **_arg1, &_arg2); end
  def asset_host=(arg); end
  def assets_dir(*_arg0, **_arg1, &_arg2); end
  def assets_dir=(arg); end
  def attachments; end
  def default_asset_host_protocol(*_arg0, **_arg1, &_arg2); end
  def default_asset_host_protocol=(arg); end
  def default_params; end
  def default_params=(_arg0); end
  def default_params?; end
  def default_static_extension(*_arg0, **_arg1, &_arg2); end
  def default_static_extension=(arg); end
  def deliver_later_queue_name; end
  def deliver_later_queue_name=(_arg0); end
  def deliver_later_queue_name?; end
  def delivery_job; end
  def delivery_job=(_arg0); end
  def delivery_job?; end
  def delivery_method; end
  def delivery_method=(_arg0); end
  def delivery_method?; end
  def delivery_methods; end
  def delivery_methods=(_arg0); end
  def delivery_methods?; end
  def email_address_with_name(address, name); end
  def enable_fragment_cache_logging(*_arg0, **_arg1, &_arg2); end
  def enable_fragment_cache_logging=(arg); end
  def file_settings; end
  def file_settings=(_arg0); end
  def file_settings?; end
  def fragment_cache_keys; end
  def fragment_cache_keys=(_arg0); end
  def fragment_cache_keys?; end
  def headers(args = T.unsafe(nil)); end
  def javascripts_dir(*_arg0, **_arg1, &_arg2); end
  def javascripts_dir=(arg); end
  def logger(*_arg0, **_arg1, &_arg2); end
  def logger=(arg); end
  def mail(headers = T.unsafe(nil), &block); end
  def mailer_name; end
  def message; end
  def message=(_arg0); end
  def params; end
  def params=(_arg0); end
  def perform_caching(*_arg0, **_arg1, &_arg2); end
  def perform_caching=(arg); end
  def perform_deliveries; end
  def perform_deliveries=(val); end
  def preview_interceptors; end
  def preview_paths; end
  def process(method_name, *args, **_arg2); end
  def raise_delivery_errors; end
  def raise_delivery_errors=(val); end
  def raise_on_missing_callback_actions; end
  def raise_on_missing_callback_actions=(val); end
  def relative_url_root(*_arg0, **_arg1, &_arg2); end
  def relative_url_root=(arg); end
  def rescue_handlers; end
  def rescue_handlers=(_arg0); end
  def rescue_handlers?; end
  def sendmail_settings; end
  def sendmail_settings=(_arg0); end
  def sendmail_settings?; end
  def show_previews; end
  def smtp_settings; end
  def smtp_settings=(_arg0); end
  def smtp_settings?; end
  def stylesheets_dir(*_arg0, **_arg1, &_arg2); end
  def stylesheets_dir=(arg); end
  def test_settings; end
  def test_settings=(_arg0); end
  def test_settings?; end

  private

  def _layout(lookup_context, formats, keys); end
  def _protected_ivars; end
  def apply_defaults(headers); end
  def assign_headers_to_message(message, headers); end
  def collect_responses(headers, &block); end
  def collect_responses_from_block(headers); end
  def collect_responses_from_templates(headers); end
  def collect_responses_from_text(headers); end
  def compute_default(value); end
  def create_parts_from_responses(m, responses); end
  def default_i18n_subject(interpolations = T.unsafe(nil)); end
  def each_template(paths, name, &block); end
  def insert_part(container, response, charset); end
  def instrument_name; end
  def instrument_payload(key); end
  def set_content_type(m, user_content_type, class_default); end
  def wrap_inline_attachments(message); end

  class << self
    def __callbacks; end
    def __callbacks=(value); end
    def _default_form_builder; end
    def _default_form_builder=(value); end
    def _default_form_builder?; end
    def _deliver_callbacks; end
    def _deliver_callbacks=(value); end
    def _helper_methods; end
    def _helper_methods=(value); end
    def _helper_methods?; end
    def _helpers; end
    def _layout; end
    def _layout=(value); end
    def _layout?; end
    def _layout_conditions; end
    def _layout_conditions=(value); end
    def _layout_conditions?; end
    def _process_action_callbacks; end
    def _process_action_callbacks=(value); end
    def _view_cache_dependencies; end
    def _view_cache_dependencies=(value); end
    def _view_cache_dependencies?; end
    def asset_host(*_arg0, **_arg1, &_arg2); end
    def asset_host=(arg); end
    def assets_dir(*_arg0, **_arg1, &_arg2); end
    def assets_dir=(arg); end
    def controller_path; end
    def default(value = T.unsafe(nil)); end
    def default_asset_host_protocol(*_arg0, **_arg1, &_arg2); end
    def default_asset_host_protocol=(arg); end
    def default_options=(value = T.unsafe(nil)); end
    def default_params; end
    def default_params=(value); end
    def default_params?; end
    def default_static_extension(*_arg0, **_arg1, &_arg2); end
    def default_static_extension=(arg); end
    def deliver_later_queue_name; end
    def deliver_later_queue_name=(value); end
    def deliver_later_queue_name?; end
    def deliver_mail(mail); end
    def delivery_job; end
    def delivery_job=(value); end
    def delivery_job?; end
    def delivery_method; end
    def delivery_method=(value); end
    def delivery_method?; end
    def delivery_methods; end
    def delivery_methods=(value); end
    def delivery_methods?; end
    def email_address_with_name(address, name); end
    def enable_fragment_cache_logging(*_arg0, **_arg1, &_arg2); end
    def enable_fragment_cache_logging=(arg); end
    def file_settings; end
    def file_settings=(value); end
    def file_settings?; end
    def fragment_cache_keys; end
    def fragment_cache_keys=(value); end
    def fragment_cache_keys?; end
    def javascripts_dir(*_arg0, **_arg1, &_arg2); end
    def javascripts_dir=(arg); end
    def logger(*_arg0, **_arg1, &_arg2); end
    def logger=(arg); end
    def mailer_name; end
    def mailer_name=(_arg0); end
    def perform_caching(*_arg0, **_arg1, &_arg2); end
    def perform_caching=(arg); end
    def perform_deliveries; end
    def perform_deliveries=(val); end
    def preview_interceptors; end
    def preview_interceptors=(val); end
    def preview_paths; end
    def preview_paths=(val); end
    def raise_delivery_errors; end
    def raise_delivery_errors=(val); end
    def raise_on_missing_callback_actions; end
    def raise_on_missing_callback_actions=(val); end
    def register_interceptor(interceptor); end
    def register_interceptors(*interceptors); end
    def register_observer(observer); end
    def register_observers(*observers); end
    def relative_url_root(*_arg0, **_arg1, &_arg2); end
    def relative_url_root=(arg); end
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end
    def sendmail_settings; end
    def sendmail_settings=(value); end
    def sendmail_settings?; end
    def show_previews; end
    def show_previews=(val); end
    def smtp_settings; end
    def smtp_settings=(value); end
    def smtp_settings?; end
    def stylesheets_dir(*_arg0, **_arg1, &_arg2); end
    def stylesheets_dir=(arg); end
    def supports_path?; end
    def test_settings; end
    def test_settings=(value); end
    def test_settings?; end
    def unregister_interceptor(interceptor); end
    def unregister_interceptors(*interceptors); end
    def unregister_observer(observer); end
    def unregister_observers(*observers); end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__default_form_builder; end
    def __class_attr__default_form_builder=(new_value); end
    def __class_attr__helper_methods; end
    def __class_attr__helper_methods=(new_value); end
    def __class_attr__layout; end
    def __class_attr__layout=(new_value); end
    def __class_attr__layout_conditions; end
    def __class_attr__layout_conditions=(new_value); end
    def __class_attr__view_cache_dependencies; end
    def __class_attr__view_cache_dependencies=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_default_params; end
    def __class_attr_default_params=(new_value); end
    def __class_attr_deliver_later_queue_name; end
    def __class_attr_deliver_later_queue_name=(new_value); end
    def __class_attr_delivery_job; end
    def __class_attr_delivery_job=(new_value); end
    def __class_attr_delivery_method; end
    def __class_attr_delivery_method=(new_value); end
    def __class_attr_delivery_methods; end
    def __class_attr_delivery_methods=(new_value); end
    def __class_attr_file_settings; end
    def __class_attr_file_settings=(new_value); end
    def __class_attr_fragment_cache_keys; end
    def __class_attr_fragment_cache_keys=(new_value); end
    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
    def __class_attr_sendmail_settings; end
    def __class_attr_sendmail_settings=(new_value); end
    def __class_attr_smtp_settings; end
    def __class_attr_smtp_settings=(new_value); end
    def __class_attr_test_settings; end
    def __class_attr_test_settings=(new_value); end
    def method_missing(method_name, *_arg1, **_arg2, &_arg3); end
    def observer_class_for(value); end
    def respond_to_missing?(method, include_all = T.unsafe(nil)); end
    def set_payload_for_mail(payload, mail); end
  end
end

module ActionMailer::Base::HelperMethods
  include ::ActionMailer::MailHelper

  def combined_fragment_cache_key(*_arg0, **_arg1, &_arg2); end
  def view_cache_dependencies(*_arg0, **_arg1, &_arg2); end
end

class ActionMailer::Base::LateAttachmentsProxy < ::SimpleDelegator
  def []=(_name, _content); end
  def inline; end

  private

  def _raise_error; end
end

class ActionMailer::Base::NullMail
  def body; end
  def header; end
  def method_missing(*_arg0, **_arg1, &_arg2); end
  def respond_to?(string, include_all = T.unsafe(nil)); end
end

ActionMailer::Base::PROTECTED_IVARS = T.let(T.unsafe(nil), Array)

module ActionMailer::Callbacks
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::ActiveSupport::Callbacks

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActionMailer::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::DescendantsTracker

  module GeneratedClassMethods
    def __callbacks; end
    def __callbacks=(value); end
  end

  module GeneratedInstanceMethods
    def __callbacks; end
  end
end

module ActionMailer::Callbacks::ClassMethods
  def after_deliver(*filters, &blk); end
  def around_deliver(*filters, &blk); end
  def before_deliver(*filters, &blk); end
  def internal_methods; end
end

ActionMailer::Callbacks::DEFAULT_INTERNAL_METHODS = T.let(T.unsafe(nil), Array)

class ActionMailer::Collector
  include ::AbstractController::Collector

  def initialize(context, &block); end

  def all(*args, &block); end
  def any(*args, &block); end
  def custom(mime, options = T.unsafe(nil)); end
  def responses; end
end

module ActionMailer::DeliveryMethods
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActionMailer::DeliveryMethods::ClassMethods

  def wrap_delivery_behavior!(*args); end

  module GeneratedClassMethods
    def delivery_method; end
    def delivery_method=(value); end
    def delivery_method?; end
    def delivery_methods; end
    def delivery_methods=(value); end
    def delivery_methods?; end
    def file_settings; end
    def file_settings=(value); end
    def file_settings?; end
    def sendmail_settings; end
    def sendmail_settings=(value); end
    def sendmail_settings?; end
    def smtp_settings; end
    def smtp_settings=(value); end
    def smtp_settings?; end
    def test_settings; end
    def test_settings=(value); end
    def test_settings?; end
  end

  module GeneratedInstanceMethods
    def delivery_method; end
    def delivery_method=(value); end
    def delivery_method?; end
    def delivery_methods; end
    def delivery_methods=(value); end
    def delivery_methods?; end
    def file_settings; end
    def file_settings=(value); end
    def file_settings?; end
    def sendmail_settings; end
    def sendmail_settings=(value); end
    def sendmail_settings?; end
    def smtp_settings; end
    def smtp_settings=(value); end
    def smtp_settings?; end
    def test_settings; end
    def test_settings=(value); end
    def test_settings?; end
  end
end

module ActionMailer::DeliveryMethods::ClassMethods
  def add_delivery_method(symbol, klass, default_options = T.unsafe(nil)); end
  def deliveries(&_arg0); end
  def deliveries=(arg); end
  def wrap_delivery_behavior(mail, method = T.unsafe(nil), options = T.unsafe(nil)); end
end

module ActionMailer::FormBuilder
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActionMailer::FormBuilder::ClassMethods

  def default_form_builder; end

  module GeneratedClassMethods
    def _default_form_builder; end
    def _default_form_builder=(value); end
    def _default_form_builder?; end
  end

  module GeneratedInstanceMethods; end
end

module ActionMailer::FormBuilder::ClassMethods
  def default_form_builder(builder); end
end

class ActionMailer::InlinePreviewInterceptor
  include ::Base64

  def initialize(message); end

  def transform!; end

  private

  def data_url(part); end
  def find_part(cid); end
  def html_part; end
  def message; end

  class << self
    def previewing_email(message); end
  end
end

ActionMailer::InlinePreviewInterceptor::PATTERN = T.let(T.unsafe(nil), Regexp)

class ActionMailer::LogSubscriber < ::ActiveSupport::LogSubscriber
  def deliver(event); end
  def logger; end
  def process(event); end

  class << self
    private

    def __class_attr_log_levels; end
    def __class_attr_log_levels=(new_value); end
  end
end

class ActionMailer::MailDeliveryJob < ::ActiveJob::Base
  def perform(mailer, mail_method, delivery_method, args:, kwargs: T.unsafe(nil), params: T.unsafe(nil)); end

  private

  def handle_exception_with_mailer_class(exception); end
  def mailer_class; end

  class << self
    private

    def __class_attr_queue_name; end
    def __class_attr_queue_name=(new_value); end
    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

module ActionMailer::MailHelper
  def attachments; end
  def block_format(text); end
  def format_paragraph(text, len = T.unsafe(nil), indent = T.unsafe(nil)); end
  def mailer; end
  def message; end
end

class ActionMailer::MessageDelivery
  def initialize(mailer_class, action, *args, **_arg3); end

  def __getobj__; end
  def __setobj__(mail_message); end
  def action; end
  def args; end
  def deliver_later(options = T.unsafe(nil)); end
  def deliver_later!(options = T.unsafe(nil)); end
  def deliver_now; end
  def deliver_now!; end
  def mailer_class; end
  def message; end
  def params; end
  def processed?; end

  private

  def enqueue_delivery(delivery_method, options = T.unsafe(nil)); end
  def processed_mailer; end
end

class ActionMailer::NonInferrableMailerError < ::StandardError
  def initialize(name); end
end

module ActionMailer::Parameterized
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionMailer::Parameterized::ClassMethods
end

module ActionMailer::Parameterized::ClassMethods
  def with(params); end
end

class ActionMailer::Parameterized::Mailer
  def initialize(mailer, params); end

  private

  def method_missing(method_name, *_arg1, **_arg2, &_arg3); end
  def respond_to_missing?(method, include_all = T.unsafe(nil)); end
end

class ActionMailer::Parameterized::MessageDelivery < ::ActionMailer::MessageDelivery
  def initialize(mailer_class, action, params, *_arg3, **_arg4, &_arg5); end

  private

  def enqueue_delivery(delivery_method, options = T.unsafe(nil)); end
  def processed_mailer; end
end

class ActionMailer::Preview
  extend ::ActiveSupport::DescendantsTracker

  def initialize(params = T.unsafe(nil)); end

  def params; end

  class << self
    def all; end
    def call(email, params = T.unsafe(nil)); end
    def email_exists?(email); end
    def emails; end
    def exists?(preview); end
    def find(preview); end
    def preview_name; end

    private

    def inform_preview_interceptors(message); end
    def load_previews; end
    def preview_paths; end
    def show_previews; end
  end
end

module ActionMailer::Previews
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionMailer::Previews::ClassMethods
end

module ActionMailer::Previews::ClassMethods
  def register_preview_interceptor(interceptor); end
  def register_preview_interceptors(*interceptors); end
  def unregister_preview_interceptor(interceptor); end
  def unregister_preview_interceptors(*interceptors); end

  private

  def interceptor_class_for(interceptor); end
end

module ActionMailer::QueuedDelivery
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def deliver_later_queue_name; end
    def deliver_later_queue_name=(value); end
    def deliver_later_queue_name?; end
    def delivery_job; end
    def delivery_job=(value); end
    def delivery_job?; end
  end

  module GeneratedInstanceMethods
    def deliver_later_queue_name; end
    def deliver_later_queue_name=(value); end
    def deliver_later_queue_name?; end
    def delivery_job; end
    def delivery_job=(value); end
    def delivery_job?; end
  end
end

class ActionMailer::Railtie < ::Rails::Railtie; end

module ActionMailer::Rescuable
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::ActiveSupport::Rescuable

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveSupport::Rescuable::ClassMethods
  mixes_in_class_methods ::ActionMailer::Rescuable::ClassMethods

  def handle_exceptions; end

  private

  def process(*_arg0, **_arg1, &_arg2); end

  module GeneratedClassMethods
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end
  end

  module GeneratedInstanceMethods
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end
  end
end

module ActionMailer::Rescuable::ClassMethods
  def handle_exception(exception); end
end

class ActionMailer::StructuredEventSubscriber < ::ActiveSupport::StructuredEventSubscriber
  def deliver(event); end
  def process(event); end
end

class ActionMailer::TestCase < ::ActiveSupport::TestCase
  include ::ActiveSupport::Testing::ConstantLookup
  include ::ActiveJob::TestHelper
  include ::ActionMailer::TestHelper
  include ::Rails::Dom::Testing::Assertions::SelectorAssertions
  include ::Rails::Dom::Testing::Assertions::DomAssertions
  include ::ActionMailer::TestCase::Behavior
  extend ::ActiveSupport::Testing::ConstantLookup::ClassMethods
  extend ::ActionMailer::TestCase::Behavior::ClassMethods

  def _mailer_class; end
  def _mailer_class=(_arg0); end
  def _mailer_class?; end
  def _run_setup_callbacks(&block); end
  def _run_teardown_callbacks(&block); end

  class << self
    def _mailer_class; end
    def _mailer_class=(value); end
    def _mailer_class?; end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__mailer_class; end
    def __class_attr__mailer_class=(new_value); end
  end
end

module ActionMailer::TestCase::Behavior
  include ::ActiveSupport::Testing::Assertions
  include ::ActiveJob::TestHelper
  include ::ActionMailer::TestHelper
  include ::Rails::Dom::Testing::Assertions::SelectorAssertions
  include ::Rails::Dom::Testing::Assertions::DomAssertions
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::ActiveSupport::Testing::ConstantLookup

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveSupport::Testing::ConstantLookup::ClassMethods
  mixes_in_class_methods ::ActionMailer::TestCase::Behavior::ClassMethods

  def read_fixture(action); end

  private

  def charset; end
  def encode(subject); end
  def initialize_test_deliveries; end
  def restore_delivery_method; end
  def restore_test_deliveries; end
  def set_delivery_method(method); end
  def set_expected_mail; end

  module GeneratedClassMethods
    def _mailer_class; end
    def _mailer_class=(value); end
    def _mailer_class?; end
  end

  module GeneratedInstanceMethods
    def _mailer_class; end
    def _mailer_class=(value); end
    def _mailer_class?; end
  end
end

module ActionMailer::TestCase::Behavior::ClassMethods
  def determine_default_mailer(name); end
  def mailer_class; end
  def tests(mailer); end
end

module ActionMailer::TestCase::ClearTestDeliveries
  extend ::ActiveSupport::Concern

  private

  def clear_test_deliveries; end
end

module ActionMailer::TestHelper
  include ::ActiveSupport::Testing::Assertions
  include ::ActiveJob::TestHelper

  def assert_emails(number, &block); end
  def assert_enqueued_email_with(mailer, method, params: T.unsafe(nil), args: T.unsafe(nil), queue: T.unsafe(nil), &block); end
  def assert_enqueued_emails(number, &block); end
  def assert_no_emails(&block); end
  def assert_no_enqueued_emails(&block); end
  def capture_emails(&block); end
  def deliver_enqueued_emails(queue: T.unsafe(nil), at: T.unsafe(nil), &block); end

  private

  def delivery_job_filter(job); end
end

module ActionMailer::VERSION; end
ActionMailer::VERSION::MAJOR = T.let(T.unsafe(nil), Integer)
ActionMailer::VERSION::MINOR = T.let(T.unsafe(nil), Integer)
ActionMailer::VERSION::PRE = T.let(T.unsafe(nil), T.untyped)
ActionMailer::VERSION::STRING = T.let(T.unsafe(nil), String)
ActionMailer::VERSION::TINY = T.let(T.unsafe(nil), Integer)
