# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activestorage` gem.
# Please instead update this file by running `bin/tapioca gem activestorage`.


module ActiveStorage
  extend ::ActiveSupport::Autoload

  def analyzers; end
  def analyzers=(val); end
  def binary_content_type; end
  def binary_content_type=(val); end
  def content_types_allowed_inline; end
  def content_types_allowed_inline=(val); end
  def content_types_to_serve_as_binary; end
  def content_types_to_serve_as_binary=(val); end
  def draw_routes; end
  def draw_routes=(val); end
  def logger; end
  def logger=(val); end
  def paths; end
  def paths=(val); end
  def previewers; end
  def previewers=(val); end
  def queues; end
  def queues=(val); end
  def resolve_model_to_route; end
  def resolve_model_to_route=(val); end
  def routes_prefix; end
  def routes_prefix=(val); end
  def service_urls_expire_in; end
  def service_urls_expire_in=(val); end
  def streaming_chunk_max_size; end
  def streaming_chunk_max_size=(val); end
  def supported_image_processing_methods; end
  def supported_image_processing_methods=(val); end
  def touch_attachment_records; end
  def touch_attachment_records=(val); end
  def track_variants; end
  def track_variants=(val); end
  def unsupported_image_processing_arguments; end
  def unsupported_image_processing_arguments=(val); end
  def urls_expire_in; end
  def urls_expire_in=(val); end
  def variable_content_types; end
  def variable_content_types=(val); end
  def variant_processor; end
  def variant_processor=(val); end
  def variant_transformer; end
  def variant_transformer=(val); end
  def verifier; end
  def verifier=(val); end
  def video_preview_arguments; end
  def video_preview_arguments=(val); end
  def web_image_content_types; end
  def web_image_content_types=(val); end

  class << self
    def analyzers; end
    def analyzers=(val); end
    def binary_content_type; end
    def binary_content_type=(val); end
    def checksum_implementation; end
    def checksum_implementation=(_arg0); end
    def content_types_allowed_inline; end
    def content_types_allowed_inline=(val); end
    def content_types_to_serve_as_binary; end
    def content_types_to_serve_as_binary=(val); end
    def deprecator; end
    def draw_routes; end
    def draw_routes=(val); end
    def gem_version; end
    def logger; end
    def logger=(val); end
    def paths; end
    def paths=(val); end
    def previewers; end
    def previewers=(val); end
    def queues; end
    def queues=(val); end
    def resolve_model_to_route; end
    def resolve_model_to_route=(val); end
    def routes_prefix; end
    def routes_prefix=(val); end
    def service_urls_expire_in; end
    def service_urls_expire_in=(val); end
    def streaming_chunk_max_size; end
    def streaming_chunk_max_size=(val); end
    def streaming_max_ranges; end
    def streaming_max_ranges=(_arg0); end
    def supported_image_processing_methods; end
    def supported_image_processing_methods=(val); end
    def touch_attachment_records; end
    def touch_attachment_records=(val); end
    def track_variants; end
    def track_variants=(val); end
    def unsupported_image_processing_arguments; end
    def unsupported_image_processing_arguments=(val); end
    def urls_expire_in; end
    def urls_expire_in=(val); end
    def variable_content_types; end
    def variable_content_types=(val); end
    def variant_processor; end
    def variant_processor=(val); end
    def variant_transformer; end
    def variant_transformer=(val); end
    def verifier; end
    def verifier=(val); end
    def version; end
    def video_preview_arguments; end
    def video_preview_arguments=(val); end
    def web_image_content_types; end
    def web_image_content_types=(val); end
  end
end

class ActiveStorage::Analyzer
  def initialize(blob); end

  def blob; end
  def metadata; end

  private

  def download_blob_to_tempfile(&block); end
  def instrument(analyzer, &block); end
  def logger; end
  def tmpdir; end

  class << self
    def accept?(blob); end
    def analyze_later?; end
  end
end

class ActiveStorage::Attached
  def initialize(name, record); end

  def name; end
  def record; end

  private

  def change; end
end

module ActiveStorage::Attached::Changes
  extend ::ActiveSupport::Autoload
end

class ActiveStorage::Attached::Changes::CreateMany
  def initialize(name, record, attachables, pending_uploads: T.unsafe(nil)); end

  def attachables; end
  def attachments; end
  def blobs; end
  def name; end
  def pending_uploads; end
  def record; end
  def save; end
  def upload; end

  private

  def assign_associated_attachments; end
  def build_subchange_from(attachable); end
  def persisted_or_new_attachments; end
  def reset_associated_blobs; end
  def subchanges; end
  def subchanges_without_blobs; end
end

class ActiveStorage::Attached::Changes::CreateOne
  def initialize(name, record, attachable); end

  def attachable; end
  def attachment; end
  def blob; end
  def name; end
  def record; end
  def save; end
  def upload; end

  private

  def attachment_service_name; end
  def build_attachment; end
  def find_attachment; end
  def find_or_build_attachment; end
  def find_or_build_blob; end
end

class ActiveStorage::Attached::Changes::CreateOneOfMany < ::ActiveStorage::Attached::Changes::CreateOne
  private

  def find_attachment; end
end

class ActiveStorage::Attached::Changes::DeleteMany
  def initialize(name, record); end

  def attachables; end
  def attachments; end
  def blobs; end
  def name; end
  def record; end
  def save; end
end

class ActiveStorage::Attached::Changes::DeleteOne
  def initialize(name, record); end

  def attachment; end
  def name; end
  def record; end
  def save; end
end

class ActiveStorage::Attached::Changes::DetachMany
  def initialize(name, record, attachments); end

  def attachments; end
  def detach; end
  def name; end
  def record; end
end

class ActiveStorage::Attached::Changes::DetachOne
  def initialize(name, record, attachment); end

  def attachment; end
  def detach; end
  def name; end
  def record; end

  private

  def reset; end
end

class ActiveStorage::Attached::Changes::PurgeMany
  def initialize(name, record, attachments); end

  def attachments; end
  def name; end
  def purge; end
  def purge_later; end
  def record; end

  private

  def reset; end
end

class ActiveStorage::Attached::Changes::PurgeOne
  def initialize(name, record, attachment); end

  def attachment; end
  def name; end
  def purge; end
  def purge_later; end
  def record; end

  private

  def reset; end
end

class ActiveStorage::Attached::Many < ::ActiveStorage::Attached
  def attach(*attachables); end
  def attached?; end
  def attachments; end
  def blobs; end
  def detach(*_arg0, **_arg1, &_arg2); end
  def method_missing(method, *_arg1, **_arg2, &_arg3); end
  def purge(*_arg0, **_arg1, &_arg2); end
  def purge_later(*_arg0, **_arg1, &_arg2); end

  private

  def detach_many; end
  def purge_many; end
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

module ActiveStorage::Attached::Model
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActiveStorage::Attached::Model::ClassMethods

  def attachment_changes; end
  def changed_for_autosave?; end
  def reload(*_arg0); end

  private

  def initialize_dup(*_arg0); end

  class << self
    def validate_service_configuration(service_name, model_class, association_name); end

    private

    def validate_global_service_configuration(model_class); end
  end
end

module ActiveStorage::Attached::Model::ClassMethods
  def has_many_attached(name, dependent: T.unsafe(nil), service: T.unsafe(nil), strict_loading: T.unsafe(nil)); end
  def has_one_attached(name, dependent: T.unsafe(nil), service: T.unsafe(nil), strict_loading: T.unsafe(nil)); end
end

class ActiveStorage::Attached::One < ::ActiveStorage::Attached
  def attach(attachable); end
  def attached?; end
  def attachment; end
  def blank?; end
  def detach(*_arg0, **_arg1, &_arg2); end
  def method_missing(method, *_arg1, **_arg2, &_arg3); end
  def purge(*_arg0, **_arg1, &_arg2); end
  def purge_later(*_arg0, **_arg1, &_arg2); end

  private

  def detach_one; end
  def purge_one; end
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

class ActiveStorage::Downloader
  def initialize(service); end

  def open(key, checksum: T.unsafe(nil), verify: T.unsafe(nil), name: T.unsafe(nil), tmpdir: T.unsafe(nil)); end
  def service; end

  private

  def download(key, file); end
  def open_tempfile(name, tmpdir = T.unsafe(nil)); end
  def verify_integrity_of(file, checksum:); end
end

class ActiveStorage::Error < ::StandardError; end
class ActiveStorage::FileNotFoundError < ::ActiveStorage::Error; end

class ActiveStorage::FixtureSet
  include ::ActiveSupport::Testing::FileFixtures
  include ::ActiveRecord::SecureToken
  extend ::ActiveRecord::SecureToken::ClassMethods

  def file_fixture_path; end
  def file_fixture_path?; end
  def prepare(instance, **attributes); end

  class << self
    def blob(filename:, **attributes); end
    def file_fixture_path; end
    def file_fixture_path=(value); end
    def file_fixture_path?; end

    private

    def __class_attr_file_fixture_path; end
    def __class_attr_file_fixture_path=(new_value); end
  end
end

class ActiveStorage::IntegrityError < ::ActiveStorage::Error; end
class ActiveStorage::InvalidKeyError < ::ActiveStorage::Error; end
class ActiveStorage::InvariableError < ::ActiveStorage::Error; end

class ActiveStorage::LogSubscriber < ::ActiveSupport::LogSubscriber
  def logger; end
  def preview(event); end
  def service_delete(event); end
  def service_delete_prefixed(event); end
  def service_download(event); end
  def service_exist(event); end
  def service_mirror(event); end
  def service_streaming_download(event); end
  def service_upload(event); end
  def service_url(event); end

  private

  def debug(event, colored_message); end
  def info(event, colored_message); end
  def key_in(event); end
  def log_prefix_for_service(event); end

  class << self
    private

    def __class_attr_log_levels; end
    def __class_attr_log_levels=(new_value); end
  end
end

class ActiveStorage::PreviewError < ::ActiveStorage::Error; end

class ActiveStorage::Previewer
  def initialize(blob); end

  def blob; end
  def preview(**options); end

  private

  def capture(*argv, to:); end
  def download_blob_to_tempfile(&block); end
  def draw(*argv); end
  def instrument(operation, payload = T.unsafe(nil), &block); end
  def logger; end
  def open_tempfile; end
  def service_name; end
  def tmpdir; end

  class << self
    def accept?(blob); end
  end
end

module ActiveStorage::Reflection; end

module ActiveStorage::Reflection::ActiveRecordExtensions
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveStorage::Reflection::ActiveRecordExtensions::ClassMethods

  module GeneratedClassMethods
    def attachment_reflections; end
    def attachment_reflections=(value); end
    def attachment_reflections?; end
  end

  module GeneratedInstanceMethods
    def attachment_reflections; end
    def attachment_reflections?; end
  end
end

module ActiveStorage::Reflection::ActiveRecordExtensions::ClassMethods
  def reflect_on_all_attachments; end
  def reflect_on_attachment(attachment); end
end

class ActiveStorage::Reflection::HasAttachedReflection < ::ActiveRecord::Reflection::MacroReflection
  def named_variants; end
  def variant(name, transformations); end
end

class ActiveStorage::Reflection::HasManyAttachedReflection < ::ActiveStorage::Reflection::HasAttachedReflection
  def macro; end
end

class ActiveStorage::Reflection::HasOneAttachedReflection < ::ActiveStorage::Reflection::HasAttachedReflection
  def macro; end
end

module ActiveStorage::Reflection::ReflectionExtension
  def add_attachment_reflection(model, name, reflection); end

  private

  def reflection_class_for(macro); end
end

class ActiveStorage::Service
  extend ::ActiveSupport::Autoload

  def compose(source_keys, destination_key, filename: T.unsafe(nil), content_type: T.unsafe(nil), disposition: T.unsafe(nil), custom_metadata: T.unsafe(nil)); end
  def delete(key); end
  def delete_prefixed(prefix); end
  def download(key); end
  def download_chunk(key, range); end
  def exist?(key); end
  def headers_for_direct_upload(key, filename:, content_type:, content_length:, checksum:, custom_metadata: T.unsafe(nil)); end
  def inspect; end
  def name; end
  def name=(_arg0); end
  def open(*args, **options, &block); end
  def public?; end
  def update_metadata(key, **metadata); end
  def upload(key, io, checksum: T.unsafe(nil), **options); end
  def url(key, **options); end
  def url_for_direct_upload(key, expires_in:, content_type:, content_length:, checksum:, custom_metadata: T.unsafe(nil)); end

  private

  def content_disposition_with(filename:, type: T.unsafe(nil)); end
  def custom_metadata_headers(metadata); end
  def instrument(operation, payload = T.unsafe(nil), &block); end
  def private_url(key, expires_in:, filename:, disposition:, content_type:, **_arg5); end
  def public_url(key, **_arg1); end
  def service_name; end

  class << self
    def build(configurator:, name:, service: T.unsafe(nil), **service_config); end
    def configure(service_name, configurations); end
  end
end

class ActiveStorage::Service::Configurator
  def initialize(configurations); end

  def build(service_name); end
  def configurations; end
  def inspect; end

  private

  def config_for(name); end
  def resolve(class_name); end

  class << self
    def build(service_name, configurations); end
  end
end

class ActiveStorage::StructuredEventSubscriber < ::ActiveSupport::StructuredEventSubscriber
  def preview(event); end
  def service_delete(event); end
  def service_delete_prefixed(event); end
  def service_download(event); end
  def service_exist(event); end
  def service_mirror(event); end
  def service_streaming_download(event); end
  def service_upload(event); end
  def service_url(event); end
end

module ActiveStorage::Transformers
  extend ::ActiveSupport::Autoload
end

class ActiveStorage::Transformers::NullTransformer < ::ActiveStorage::Transformers::Transformer
  private

  def process(file, format:); end
end

class ActiveStorage::Transformers::Transformer
  def initialize(transformations); end

  def transform(file, format:); end
  def transformations; end

  private

  def process(file, format:); end
end

class ActiveStorage::UnpreviewableError < ::ActiveStorage::Error; end
class ActiveStorage::UnrepresentableError < ::ActiveStorage::Error; end
module ActiveStorage::VERSION; end
ActiveStorage::VERSION::MAJOR = T.let(T.unsafe(nil), Integer)
ActiveStorage::VERSION::MINOR = T.let(T.unsafe(nil), Integer)
ActiveStorage::VERSION::PRE = T.let(T.unsafe(nil), T.untyped)
ActiveStorage::VERSION::STRING = T.let(T.unsafe(nil), String)
ActiveStorage::VERSION::TINY = T.let(T.unsafe(nil), Integer)
