# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `attr_json` gem.
# Please instead update this file by running `bin/tapioca gem attr_json`.


module AttrJson
  class << self
    def efficient_to_s(obj); end
  end
end

class AttrJson::AttributeDefinition
  def initialize(name, type, options = T.unsafe(nil)); end

  def array_of_primitive_type?; end
  def array_type?; end
  def cast(value); end
  def container_attribute; end
  def default_argument; end
  def deserialize(value); end
  def has_custom_store_key?; end
  def has_default?; end
  def name; end
  def original_args; end
  def provide_default!; end
  def serialize(value); end
  def single_model_type?; end
  def store_key; end
  def type; end

  class << self
    def lookup_type(type); end
    def single_model_type?(arg_type); end
  end
end

AttrJson::AttributeDefinition::NO_DEFAULT_PROVIDED = T.let(T.unsafe(nil), Object)

class AttrJson::AttributeDefinition::Registry
  def initialize(hash = T.unsafe(nil)); end

  def [](key); end
  def attribute_names; end
  def container_attribute_registered?(attribute_name:, model:); end
  def container_attributes; end
  def definitions; end
  def fetch(key, *args, &block); end
  def has_attribute?(key); end
  def register_container_attribute(attribute_name:, model:); end
  def store_key_lookup(container_attribute, store_key); end
  def type_for_attribute(key); end
  def with(*definitions); end

  protected

  def add!(definition); end
  def store_key_index!(definition); end
end

AttrJson::AttributeDefinition::VALID_OPTIONS = T.let(T.unsafe(nil), Array)

class AttrJson::Config
  def initialize(options = T.unsafe(nil)); end

  def bad_cast; end
  def default_accepts_nested_attributes; end
  def default_container_attribute; end
  def merge(changes = T.unsafe(nil)); end
  def mode; end
  def time_zone_aware_attributes; end
  def unknown_key; end

  protected

  def attributes; end
end

AttrJson::Config::DEFAULTS = T.let(T.unsafe(nil), Hash)
AttrJson::Config::MODEL_ALLOWED_KEYS = T.let(T.unsafe(nil), Array)
AttrJson::Config::RECORD_ALLOWED_KEYS = T.let(T.unsafe(nil), Array)

module AttrJson::Model
  include ::ActiveModel::Serialization
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::Validations::HelperMethods
  include ::ActiveModel::Validations
  include ::ActiveModel::Conversion
  include ::ActiveModel::API
  include ::ActiveModel::Model

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveModel::Validations::ClassMethods
  mixes_in_class_methods ::ActiveModel::Callbacks
  mixes_in_class_methods ::ActiveSupport::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::DescendantsTracker
  mixes_in_class_methods ::ActiveModel::Translation
  mixes_in_class_methods ::ActiveModel::Validations::HelperMethods
  mixes_in_class_methods ::ActiveModel::Conversion::ClassMethods
  mixes_in_class_methods ::AttrJson::Model::ClassMethods

  def initialize(attributes = T.unsafe(nil)); end

  def ==(other_object); end
  def _destroy; end
  def as_json(options = T.unsafe(nil)); end
  def assign_attributes(new_attributes); end
  def attribute_names; end
  def attributes; end
  def freeze; end
  def has_attribute?(str); end
  def serializable_hash(options = T.unsafe(nil)); end
  def to_h; end
  def type_for_attribute(attr_name); end

  private

  def _attr_json_write(key, value); end
  def _attr_json_write_unknown_attribute(key, value); end
  def fill_in_defaults!; end
  def initialize_dup(other); end
  def read_attribute_for_serialization(key); end

  module GeneratedClassMethods
    def __callbacks; end
    def __callbacks=(value); end
    def _validators; end
    def _validators=(value); end
    def _validators?; end
    def attr_json_registry; end
    def attr_json_registry=(value); end
    def attr_json_registry?; end
    def param_delimiter; end
    def param_delimiter=(value); end
    def param_delimiter?; end
  end

  module GeneratedInstanceMethods
    def __callbacks; end
    def _validators; end
    def _validators?; end
    def param_delimiter=(value); end
  end
end

module AttrJson::Model::ClassMethods
  def attr_json(name, type, **options); end
  def attr_json_config(new_values = T.unsafe(nil)); end
  def attribute_names; end
  def attribute_types; end
  def new_from_serializable(attributes = T.unsafe(nil)); end
  def to_serialization_coder; end
  def to_type(strip_nils: T.unsafe(nil)); end

  private

  def _attr_json_maybe_wrap_timezone_aware(type); end
  def _attr_jsons_module; end
end

module AttrJson::Model::CocoonCompat
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::AttrJson::Model::CocoonCompat::ClassMethods

  def marked_for_destruction?; end
  def new_record?; end
end

module AttrJson::Model::CocoonCompat::ClassMethods
  def reflect_on_association(*args); end
end

class AttrJson::Model::NestedModelValidator < ::ActiveModel::EachValidator
  def validate_each(record, attribute, value); end

  private

  def valid_object?(record); end
end

module AttrJson::NestedAttributes
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::AttrJson::NestedAttributes::ClassMethods
end

class AttrJson::NestedAttributes::Builder
  def initialize(model, attr_name); end

  def attr_def; end
  def attr_name; end
  def build(params = T.unsafe(nil)); end
  def model; end
end

module AttrJson::NestedAttributes::ClassMethods
  def attr_json_accepts_nested_attributes_for(*attr_names); end
end

class AttrJson::NestedAttributes::MultiparameterAttributeWriter
  def initialize(model); end

  def assign_multiparameter_attributes(pairs); end
  def model; end

  protected

  def execute_callstack_for_multiparameter_attributes(callstack); end
  def extract_callstack_for_multiparameter_attributes(pairs); end
  def find_parameter_position(multiparameter_name); end
  def type_cast_attribute_value(multiparameter_name, value); end
end

class AttrJson::NestedAttributes::Writer
  def initialize(model, attr_name); end

  def assign_nested_attributes(attributes); end
  def attr_def; end
  def attr_name; end
  def model; end
  def nested_attributes_options(*_arg0, **_arg1, &_arg2); end

  protected

  def assign_nested_attributes_for_model_array(attributes_collection); end
  def assign_nested_attributes_for_primitive_array(attributes_array); end
  def assign_nested_attributes_for_single_model(attributes); end
  def call_reject_if(association_name, attributes); end
  def check_record_limit!(limit, attributes_collection); end
  def extract_multi_parameter_attributes(attributes); end
  def has_destroy_flag?(hash); end
  def model_send(method, *args); end
  def reject_new_record?(association_name, attributes); end
  def unassignable_keys; end
  def will_be_destroyed?(association_name, attributes); end
end

module AttrJson::Record
  extend ::ActiveSupport::Concern

  def attr_json_sync_to_rails_attributes; end
end

module AttrJson::Record::ClassMethods
  def attr_json(name, type, **options); end
  def attr_json_config(new_values = T.unsafe(nil)); end

  private

  def _attr_jsons_module; end
end

class AttrJson::Record::QueryBuilder
  def initialize(relation, input_attributes); end

  def contains_not_relation; end
  def contains_relation; end
  def input_attributes; end
  def relation; end

  protected

  def add_to_param_hash!(param_hash, key_path_str, value); end
  def contains_relation_impl; end
  def group_attributes_by_container; end
  def merge_param_hash!(original, new); end
end

module AttrJson::Record::QueryScopes
  extend ::ActiveSupport::Concern
end

class AttrJson::SerializationCoderFromType
  def initialize(type); end

  def dump(value); end
  def load(value); end
  def type; end
end

module AttrJson::Type; end

class AttrJson::Type::Array < ::ActiveModel::Type::Value
  def initialize(base_type); end

  def base_type; end
  def base_type_primitive?; end
  def cast(value); end
  def changed_in_place?(raw_old_value, new_value); end
  def deserialize(value); end
  def serialize(value); end
  def type; end
  def value_for_contains_query(key_path_arr, value); end

  protected

  def convert_to_array(value); end
end

class AttrJson::Type::ContainerAttribute < ::ActiveRecord::Type::Json
  def initialize(model, container_attribute); end

  def cast(v); end
  def changed_in_place?(raw_old_value, new_value); end
  def container_attribute; end
  def deserialize(v, with_defaults: T.unsafe(nil)); end
  def model; end
  def serialize(v); end
end

class AttrJson::Type::Model < ::ActiveModel::Type::Value
  def initialize(model, strip_nils: T.unsafe(nil)); end

  def cast(v); end
  def changed_in_place?(raw_old_value, new_value); end
  def deserialize(v); end
  def model; end
  def model=(_arg0); end
  def serialize(v); end
  def strip_nils; end
  def strip_nils=(_arg0); end
  def type; end
  def value_for_contains_query(key_path_arr, value); end
end

class AttrJson::Type::Model::BadCast < ::ArgumentError; end

class AttrJson::Type::PolymorphicModel < ::ActiveModel::Type::Value
  def initialize(*args); end

  def cast(v); end
  def deserialize(v); end
  def model_names; end
  def model_type_lookup; end
  def model_types; end
  def serialize(v); end
  def type; end
  def type_for_model_name(model_name); end
  def type_key; end
  def unrecognized_type; end
  def value_for_contains_query(key_path_arr, value); end

  protected

  def cast_or_deserialize(v, operation); end
  def model_from_hash(hash, operation); end
  def raise_bad_model_name(name, value); end
  def raise_missing_type_key(value); end
end

class AttrJson::Type::PolymorphicModel::TypeError < ::TypeError; end
AttrJson::VERSION = T.let(T.unsafe(nil), String)
