# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `climate_control` gem.
# Please instead update this file by running `bin/tapioca gem climate_control`.


# pkg:gem/climate_control#lib/climate_control/environment.rb:4
module ClimateControl
  class << self
    # pkg:gem/climate_control#lib/climate_control.rb:13
    def env; end

    # pkg:gem/climate_control#lib/climate_control.rb:9
    def modify(environment_overrides, &block); end
  end
end

# pkg:gem/climate_control#lib/climate_control/environment.rb:5
class ClimateControl::Environment
  extend ::Forwardable

  # pkg:gem/climate_control#lib/climate_control/environment.rb:8
  def initialize; end

  # pkg:gem/climate_control#lib/climate_control/environment.rb:13
  def [](*_arg0, **_arg1, &_arg2); end

  # pkg:gem/climate_control#lib/climate_control/environment.rb:13
  def []=(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/climate_control#lib/climate_control/environment.rb:13
  def delete(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/climate_control#lib/climate_control/environment.rb:15
  def synchronize; end

  # pkg:gem/climate_control#lib/climate_control/environment.rb:13
  def to_hash(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/climate_control#lib/climate_control/environment.rb:32
  def env; end
end

# pkg:gem/climate_control#lib/climate_control/modifier.rb:2
class ClimateControl::Modifier
  # pkg:gem/climate_control#lib/climate_control/modifier.rb:3
  def initialize(env, environment_overrides = T.unsafe(nil), &block); end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:9
  def process; end

  private

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:53
  def cache_environment_after_block; end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:67
  def clone_environment; end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:34
  def copy_overrides_to_environment; end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:57
  def delete_keys_that_do_not_belong; end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:49
  def keys_changed_by_block; end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:45
  def keys_to_remove; end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:24
  def prepare_environment_for_block; end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:61
  def revert_changed_keys; end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:30
  def run_block; end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:71
  def stringify_keys(env); end
end

# pkg:gem/climate_control#lib/climate_control/modifier.rb:77
class ClimateControl::Modifier::OverlappingKeysWithChangedValues
  # pkg:gem/climate_control#lib/climate_control/modifier.rb:78
  def initialize(hash_1, hash_2); end

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:83
  def keys; end

  private

  # pkg:gem/climate_control#lib/climate_control/modifier.rb:91
  def overlapping_keys; end
end

# pkg:gem/climate_control#lib/climate_control/errors.rb:2
class ClimateControl::UnassignableValueError < ::ArgumentError; end

# pkg:gem/climate_control#lib/climate_control/version.rb:2
ClimateControl::VERSION = T.let(T.unsafe(nil), String)
