# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `draper` gem.
# Please instead update this file by running `bin/tapioca gem draper`.


module ActiveModel
  extend ::ActiveSupport::Autoload
end

class ActiveModel::Railtie < ::Rails::Railtie; end

module Draper
  extend ::Draper::Configuration

  class << self
    def setup_action_controller(base); end
    def setup_action_mailer(base); end
    def undecorate(object); end
    def undecorate_chain(object); end
  end
end

module Draper::AutomaticDelegation
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Draper::AutomaticDelegation::ClassMethods

  def delegatable?(method); end
  def method_missing(method, *args, **_arg2, &block); end

  private

  def respond_to_missing?(method, include_private = T.unsafe(nil)); end
end

module Draper::AutomaticDelegation::ClassMethods
  def before_remove_const; end
  def delegatable?(method); end
  def method_missing(method, *args, **_arg2, &block); end

  private

  def respond_to_missing?(method, include_private = T.unsafe(nil)); end
end

class Draper::CollectionDecorator
  include ::Enumerable
  include ::Draper::ViewHelpers
  include ::Draper::QueryMethods
  extend ::Draper::ViewHelpers::ClassMethods
  extend ::Draper::Delegation

  def initialize(object, options = T.unsafe(nil)); end

  def &(*_arg0, **_arg1, &_arg2); end
  def *(*_arg0, **_arg1, &_arg2); end
  def +(*_arg0, **_arg1, &_arg2); end
  def -(*_arg0, **_arg1, &_arg2); end
  def <<(*_arg0, **_arg1, &_arg2); end
  def ==(arg); end
  def [](*_arg0, **_arg1, &_arg2); end
  def []=(*_arg0, **_arg1, &_arg2); end
  def all?(*_arg0, **_arg1, &_arg2); end
  def any?(*_arg0, **_arg1, &_arg2); end
  def append(*_arg0, **_arg1, &_arg2); end
  def as_json(*_arg0, **_arg1, &_arg2); end
  def assoc(*_arg0, **_arg1, &_arg2); end
  def at(*_arg0, **_arg1, &_arg2); end
  def bsearch(*_arg0, **_arg1, &_arg2); end
  def bsearch_index(*_arg0, **_arg1, &_arg2); end
  def chain(*_arg0, **_arg1, &_arg2); end
  def chunk(*_arg0, **_arg1, &_arg2); end
  def chunk_while(*_arg0, **_arg1, &_arg2); end
  def clear(*_arg0, **_arg1, &_arg2); end
  def collect(*_arg0, **_arg1, &_arg2); end
  def collect!(*_arg0, **_arg1, &_arg2); end
  def collect_concat(*_arg0, **_arg1, &_arg2); end
  def combination(*_arg0, **_arg1, &_arg2); end
  def compact(*_arg0, **_arg1, &_arg2); end
  def compact!(*_arg0, **_arg1, &_arg2); end
  def compact_blank(*_arg0, **_arg1, &_arg2); end
  def compact_blank!(*_arg0, **_arg1, &_arg2); end
  def concat(*_arg0, **_arg1, &_arg2); end
  def context; end
  def context=(value); end
  def count(*_arg0, **_arg1, &_arg2); end
  def cycle(*_arg0, **_arg1, &_arg2); end
  def deconstruct(*_arg0, **_arg1, &_arg2); end
  def decorated?; end
  def decorated_collection; end
  def decorated_with?(_arg0); end
  def decorator_class; end
  def delete(*_arg0, **_arg1, &_arg2); end
  def delete_at(*_arg0, **_arg1, &_arg2); end
  def delete_if(*_arg0, **_arg1, &_arg2); end
  def detect(*_arg0, **_arg1, &_arg2); end
  def difference(*_arg0, **_arg1, &_arg2); end
  def dig(*_arg0, **_arg1, &_arg2); end
  def drop(*_arg0, **_arg1, &_arg2); end
  def drop_while(*_arg0, **_arg1, &_arg2); end
  def each(*_arg0, **_arg1, &_arg2); end
  def each_cons(*_arg0, **_arg1, &_arg2); end
  def each_entry(*_arg0, **_arg1, &_arg2); end
  def each_index(*_arg0, **_arg1, &_arg2); end
  def each_slice(*_arg0, **_arg1, &_arg2); end
  def each_with_index(*_arg0, **_arg1, &_arg2); end
  def each_with_object(*_arg0, **_arg1, &_arg2); end
  def empty?(*_arg0, **_arg1, &_arg2); end
  def entries(*_arg0, **_arg1, &_arg2); end
  def exclude?(*_arg0, **_arg1, &_arg2); end
  def excluding(*_arg0, **_arg1, &_arg2); end
  def extract!(*_arg0, **_arg1, &_arg2); end
  def extract_options!(*_arg0, **_arg1, &_arg2); end
  def fetch(*_arg0, **_arg1, &_arg2); end
  def fetch_values(*_arg0, **_arg1, &_arg2); end
  def fifth(*_arg0, **_arg1, &_arg2); end
  def fill(*_arg0, **_arg1, &_arg2); end
  def filter(*_arg0, **_arg1, &_arg2); end
  def filter!(*_arg0, **_arg1, &_arg2); end
  def filter_map(*_arg0, **_arg1, &_arg2); end
  def find(*_arg0, **_arg1, &_arg2); end
  def find_all(*_arg0, **_arg1, &_arg2); end
  def find_index(*_arg0, **_arg1, &_arg2); end
  def first(*_arg0, **_arg1, &_arg2); end
  def flat_map(*_arg0, **_arg1, &_arg2); end
  def flatten(*_arg0, **_arg1, &_arg2); end
  def flatten!(*_arg0, **_arg1, &_arg2); end
  def forty_two(*_arg0, **_arg1, &_arg2); end
  def fourth(*_arg0, **_arg1, &_arg2); end
  def from(*_arg0, **_arg1, &_arg2); end
  def grep(*_arg0, **_arg1, &_arg2); end
  def grep_v(*_arg0, **_arg1, &_arg2); end
  def group_by(*_arg0, **_arg1, &_arg2); end
  def in_order_of(*_arg0, **_arg1, &_arg2); end
  def include?(*_arg0, **_arg1, &_arg2); end
  def including(*_arg0, **_arg1, &_arg2); end
  def index(*_arg0, **_arg1, &_arg2); end
  def index_by(*_arg0, **_arg1, &_arg2); end
  def index_with(*_arg0, **_arg1, &_arg2); end
  def inject(*_arg0, **_arg1, &_arg2); end
  def insert(*_arg0, **_arg1, &_arg2); end
  def intersect?(*_arg0, **_arg1, &_arg2); end
  def intersection(*_arg0, **_arg1, &_arg2); end
  def is_a?(klass); end
  def join(*_arg0, **_arg1, &_arg2); end
  def keep_if(*_arg0, **_arg1, &_arg2); end
  def kind_of?(klass); end
  def last(*_arg0, **_arg1, &_arg2); end
  def lazy(*_arg0, **_arg1, &_arg2); end
  def length(*_arg0, **_arg1, &_arg2); end
  def many?(*_arg0, **_arg1, &_arg2); end
  def map(*_arg0, **_arg1, &_arg2); end
  def map!(*_arg0, **_arg1, &_arg2); end
  def max(*_arg0, **_arg1, &_arg2); end
  def max_by(*_arg0, **_arg1, &_arg2); end
  def maximum(*_arg0, **_arg1, &_arg2); end
  def member?(*_arg0, **_arg1, &_arg2); end
  def min(*_arg0, **_arg1, &_arg2); end
  def min_by(*_arg0, **_arg1, &_arg2); end
  def minimum(*_arg0, **_arg1, &_arg2); end
  def minmax(*_arg0, **_arg1, &_arg2); end
  def minmax_by(*_arg0, **_arg1, &_arg2); end
  def none?(*_arg0, **_arg1, &_arg2); end
  def object; end
  def one?(*_arg0, **_arg1, &_arg2); end
  def pack(*_arg0, **_arg1, &_arg2); end
  def partition(*_arg0, **_arg1, &_arg2); end
  def permutation(*_arg0, **_arg1, &_arg2); end
  def pick(*_arg0, **_arg1, &_arg2); end
  def pluck(*_arg0, **_arg1, &_arg2); end
  def pop(*_arg0, **_arg1, &_arg2); end
  def prepend(*_arg0, **_arg1, &_arg2); end
  def product(*_arg0, **_arg1, &_arg2); end
  def push(*_arg0, **_arg1, &_arg2); end
  def rassoc(*_arg0, **_arg1, &_arg2); end
  def reduce(*_arg0, **_arg1, &_arg2); end
  def reject(*_arg0, **_arg1, &_arg2); end
  def reject!(*_arg0, **_arg1, &_arg2); end
  def repeated_combination(*_arg0, **_arg1, &_arg2); end
  def repeated_permutation(*_arg0, **_arg1, &_arg2); end
  def replace(other); end
  def reverse(*_arg0, **_arg1, &_arg2); end
  def reverse!(*_arg0, **_arg1, &_arg2); end
  def reverse_each(*_arg0, **_arg1, &_arg2); end
  def rfind(*_arg0, **_arg1, &_arg2); end
  def rindex(*_arg0, **_arg1, &_arg2); end
  def rotate(*_arg0, **_arg1, &_arg2); end
  def rotate!(*_arg0, **_arg1, &_arg2); end
  def sample(*_arg0, **_arg1, &_arg2); end
  def second(*_arg0, **_arg1, &_arg2); end
  def second_to_last(*_arg0, **_arg1, &_arg2); end
  def select(*_arg0, **_arg1, &_arg2); end
  def select!(*_arg0, **_arg1, &_arg2); end
  def shelljoin(*_arg0, **_arg1, &_arg2); end
  def shift(*_arg0, **_arg1, &_arg2); end
  def shuffle(*_arg0, **_arg1, &_arg2); end
  def shuffle!(*_arg0, **_arg1, &_arg2); end
  def size(*_arg0, **_arg1, &_arg2); end
  def slice(*_arg0, **_arg1, &_arg2); end
  def slice!(*_arg0, **_arg1, &_arg2); end
  def slice_after(*_arg0, **_arg1, &_arg2); end
  def slice_before(*_arg0, **_arg1, &_arg2); end
  def slice_when(*_arg0, **_arg1, &_arg2); end
  def sole(*_arg0, **_arg1, &_arg2); end
  def sort(*_arg0, **_arg1, &_arg2); end
  def sort!(*_arg0, **_arg1, &_arg2); end
  def sort_by(*_arg0, **_arg1, &_arg2); end
  def sort_by!(*_arg0, **_arg1, &_arg2); end
  def sum(*_arg0, **_arg1, &_arg2); end
  def take(*_arg0, **_arg1, &_arg2); end
  def take_while(*_arg0, **_arg1, &_arg2); end
  def tally(*_arg0, **_arg1, &_arg2); end
  def third(*_arg0, **_arg1, &_arg2); end
  def third_to_last(*_arg0, **_arg1, &_arg2); end
  def to(*_arg0, **_arg1, &_arg2); end
  def to_a(*_arg0, **_arg1, &_arg2); end
  def to_ary(*_arg0, **_arg1, &_arg2); end
  def to_formatted_s(*_arg0, **_arg1, &_arg2); end
  def to_fs(*_arg0, **_arg1, &_arg2); end
  def to_h(*_arg0, **_arg1, &_arg2); end
  def to_s; end
  def to_sentence(*_arg0, **_arg1, &_arg2); end
  def to_set(*_arg0, **_arg1, &_arg2); end
  def to_xml(*_arg0, **_arg1, &_arg2); end
  def transpose(*_arg0, **_arg1, &_arg2); end
  def union(*_arg0, **_arg1, &_arg2); end
  def uniq(*_arg0, **_arg1, &_arg2); end
  def uniq!(*_arg0, **_arg1, &_arg2); end
  def unshift(*_arg0, **_arg1, &_arg2); end
  def values_at(*_arg0, **_arg1, &_arg2); end
  def without(*_arg0, **_arg1, &_arg2); end
  def zip(*_arg0, **_arg1, &_arg2); end
  def |(*_arg0, **_arg1, &_arg2); end

  protected

  def decorate_item(item); end

  private

  def item_decorator; end

  class << self
    def decorate(*_arg0); end
  end
end

module Draper::Compatibility; end

module Draper::Compatibility::ApiOnly
  extend ::ActiveSupport::Concern
end

module Draper::Compatibility::Broadcastable
  private

  def broadcast_rendering_with_defaults(options); end
end

module Draper::Compatibility::GlobalID
  extend ::ActiveSupport::Concern
  include ::GlobalID::Identification

  mixes_in_class_methods ::Draper::Compatibility::GlobalID::ClassMethods
end

module Draper::Compatibility::GlobalID::ClassMethods
  def find(*args); end
end

module Draper::Configuration
  def configure; end
  def default_controller; end
  def default_controller=(controller); end
  def default_query_methods_strategy; end
  def default_query_methods_strategy=(strategy); end
end

module Draper::Decoratable
  include ::Draper::Decoratable::Equality
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Draper::Decoratable::ClassMethods

  def applied_decorators; end
  def decorate(options = T.unsafe(nil)); end
  def decorated?; end
  def decorated_with?(decorator_class); end
  def decorator_class; end
  def decorator_class?; end
end

module Draper::Decoratable::ClassMethods
  def ===(other); end
  def decorate(options = T.unsafe(nil)); end
  def decorator_class(called_on = T.unsafe(nil)); end
  def decorator_class?; end
end

module Draper::Decoratable::CollectionProxy
  def decorate(options = T.unsafe(nil)); end
end

module Draper::Decoratable::Equality
  def ==(other); end

  class << self
    def test(object, other); end
    def test_for_decorator(object, other); end
  end
end

class Draper::DecoratedAssociation
  def initialize(owner, association, options); end

  def call; end

  private

  def association; end
  def decorate; end
  def factory; end
  def owner; end
  def scope; end
end

module Draper::DecoratesAssigned
  def decorates_assigned(*variables); end
end

class Draper::Decorator
  include ::Draper::ViewHelpers
  include ::Draper::Compatibility::GlobalID
  include ::GlobalID::Identification
  include ::ActiveModel::Serialization
  include ::ActiveModel::Serializers::JSON
  include ::ActiveModel::Serializers::Xml
  extend ::Draper::ViewHelpers::ClassMethods
  extend ::Draper::Compatibility::GlobalID::ClassMethods
  extend ::Draper::Delegation
  extend ::ActiveModel::Naming

  def initialize(object, options = T.unsafe(nil)); end

  def ==(other); end
  def applied_decorators; end
  def attributes; end
  def blank?(*_arg0, **_arg1, &_arg2); end
  def context; end
  def context=(_arg0); end
  def decorated?; end
  def decorated_with?(decorator_class); end
  def eql?(other); end
  def hash; end
  def include_root_in_json; end
  def include_root_in_json?; end
  def instance_of?(klass); end
  def is_a?(klass); end
  def kind_of?(klass); end
  def model; end
  def model_name(&_arg0); end
  def object; end
  def present?(*_arg0, **_arg1, &_arg2); end
  def to_model; end
  def to_param(*_arg0, **_arg1, &_arg2); end
  def to_partial_path(*_arg0, **_arg1, &_arg2); end
  def to_s(*_arg0, **_arg1, &_arg2); end

  private

  def decorated_associations; end
  def handle_multiple_decoration(options); end

  class << self
    def alias_object_to_object_class_name; end
    def collection_decorator_class; end
    def collection_decorator_name; end
    def decorate(*_arg0); end
    def decorate_collection(object, options = T.unsafe(nil)); end
    def decorates(object_class); end
    def decorates_association(association, options = T.unsafe(nil)); end
    def decorates_associations(*associations); end
    def decorates_finders; end
    def delegate_all; end
    def include_root_in_json; end
    def include_root_in_json=(value); end
    def include_root_in_json?; end
    def inferred_object_class; end
    def inherited(subclass); end
    def model_name(*_arg0, **_arg1, &_arg2); end
    def object_class; end
    def object_class?; end
    def object_class_name; end

    private

    def __class_attr_include_root_in_json; end
    def __class_attr_include_root_in_json=(new_value); end
  end
end

module Draper::Delegation
  def delegate(*methods); end
end

class Draper::Factory
  def initialize(options = T.unsafe(nil)); end

  def decorate(object, options = T.unsafe(nil)); end

  private

  def decorator_class; end
  def default_options; end
end

class Draper::Factory::Worker
  def initialize(decorator_class, object); end

  def call(options); end
  def decorator; end

  private

  def collection?; end
  def decoratable?; end
  def decorator_class; end
  def decorator_method(klass); end
  def object; end
  def object_decorator; end
  def update_context(options); end
end

module Draper::Finders
  def all(options = T.unsafe(nil)); end
  def find(id, options = T.unsafe(nil)); end
  def first(options = T.unsafe(nil)); end
  def last(options = T.unsafe(nil)); end
  def method_missing(method, *args, &block); end
end

class Draper::HelperProxy
  def initialize(view_context); end

  def capture(*_arg0, **_arg1, &_arg2); end
  def method_missing(method, *args, **_arg2, &block); end

  protected

  def view_context; end

  private

  def respond_to_missing?(method, include_private = T.unsafe(nil)); end

  class << self
    def define_proxy(name); end
  end
end

module Draper::HelperSupport
  def decorate(input, &block); end
end

module Draper::LazyHelpers
  def method_missing(method, *args, **_arg2, &block); end
end

module Draper::QueryMethods
  def method_missing(method, *args, **_arg2, &block); end

  private

  def respond_to_missing?(method, include_private = T.unsafe(nil)); end
  def strategy; end
end

module Draper::QueryMethods::LoadStrategy
  class << self
    def new(name); end
  end
end

class Draper::QueryMethods::LoadStrategy::ActiveRecord
  def allowed?(method); end
end

class Draper::QueryMethods::LoadStrategy::Mongoid
  def allowed?(method); end
end

class Draper::Railtie < ::Rails::Railtie
  def initialize_view_context; end
end

class Draper::UninferrableDecoratorError < ::NameError
  def initialize(klass); end
end

class Draper::UninferrableObjectError < ::NameError
  def initialize(klass); end
end

Draper::VERSION = T.let(T.unsafe(nil), String)

module Draper::ViewContext
  def activate_draper; end
  def view_context; end

  class << self
    def build; end
    def build!; end
    def build_strategy; end
    def clear!; end
    def controller; end
    def controller=(controller); end
    def current; end
    def current=(view_context); end
    def test_strategy(name, &block); end
  end
end

module Draper::ViewContext::BuildStrategy
  class << self
    def new(name, &block); end
  end
end

class Draper::ViewContext::BuildStrategy::Fast
  def initialize(&block); end

  def call; end

  private

  def view_context_class; end
end

class Draper::ViewContext::BuildStrategy::Full
  def initialize(&block); end

  def call; end

  private

  def block; end
  def controller; end
end

module Draper::ViewHelpers
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Draper::ViewHelpers::ClassMethods

  def h; end
  def helpers; end
  def l(*args, **_arg1); end
  def localize(*args, **_arg1); end
end

module Draper::ViewHelpers::ClassMethods
  def h; end
  def helpers; end
end
