# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `fiber-storage` gem.
# Please instead update this file by running `bin/tapioca gem fiber-storage`.


class Fiber
  class << self
    def __borked_keys__; end
  end
end

module Fiber::Storage
  def initialize(*arguments, storage: T.unsafe(nil), **options, &block); end

  def __storage__; end
  def storage; end
  def storage=(hash); end
end
