# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `jsonrpc-rails` gem.
# Please instead update this file by running `bin/tapioca gem jsonrpc-rails`.


# pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:8
module JSONRPC_Rails; end

# pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:9
module JSONRPC_Rails::Middleware; end

# Rack middleware that **validates** incoming JSON-RPC 2.0 payloads
# and injects fully-typed Ruby objects (Request / Notification /
# Response) into `env[:jsonrpc]` for easy downstream use.
#
# Validation always runs on the raw Hash/Array first; objects are only
# instantiated **after** the structure has been deemed valid, so malformed
# IDs or empty batches no longer raise before we can return a proper
# -32600 “Invalid Request”.
#
# pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:18
class JSONRPC_Rails::Middleware::Validator
  # @param app [#call]
  # @param paths [Array<String, Regexp, Proc>] paths to validate
  # @param payload_validator [#valid?, #call, nil] optional protocol validator
  # @param batch_policy [Symbol] either :allow or :reject
  # @param require_json_content_type [Boolean] reject matching POST requests
  #   that do not use application/json instead of passing them downstream
  #
  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:30
  def initialize(app, paths = T.unsafe(nil), payload_validator: T.unsafe(nil), batch_policy: T.unsafe(nil), require_json_content_type: T.unsafe(nil)); end

  # Rack entry point
  #
  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:44
  def call(env); end

  private

  # ------------------ conversion to typed objects ---------------------------
  #
  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:185
  def convert_to_objects(raw); end

  # Extract ID from raw payload if possible
  #
  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:215
  def extract_id_from_raw_payload(raw); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:210
  def invalid_request_response(raw_payload); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:101
  def json_content_type?(content_type); end

  # @param error_sym [Symbol]
  # @param status    [Integer]
  # @param id       [String, Numeric, nil]
  # @param message  [String, nil]
  # @return [Array] Rack triplet
  #
  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:203
  def jsonrpc_error_response(error_sym, status: T.unsafe(nil), id: T.unsafe(nil), message: T.unsafe(nil)); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:157
  def no_conflicting_members?(obj, allowed_members); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:169
  def valid_batch_policy?(payload); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:129
  def valid_call_structure?(obj); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:149
  def valid_error_structure?(error); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:165
  def valid_id?(id); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:116
  def valid_message_structure?(obj); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:161
  def valid_params?(obj); end

  # -------------------- structure validation --------------------------------
  #
  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:108
  def valid_payload_structure?(payload); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:173
  def valid_protocol_payload?(payload); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:137
  def valid_response_structure?(obj); end

  # pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:88
  def validate_path?(path); end
end

# pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:21
JSONRPC_Rails::Middleware::Validator::BATCH_POLICIES = T.let(T.unsafe(nil), Array)

# pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:19
JSONRPC_Rails::Middleware::Validator::CONTENT_TYPE = T.let(T.unsafe(nil), String)

# pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:20
JSONRPC_Rails::Middleware::Validator::ENV_PAYLOAD_KEY = T.let(T.unsafe(nil), Symbol)

# pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/middleware/validator.rb:22
JSONRPC_Rails::Middleware::Validator::RESERVED_MEMBERS = T.let(T.unsafe(nil), Array)

# pkg:gem/jsonrpc-rails#lib/jsonrpc_rails/railtie.rb:7
class JSONRPC_Rails::Railtie < ::Rails::Railtie; end

# pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:3
module JSON_RPC; end

# Custom exception class for JSON-RPC errors, based on the JSON-RPC 2.0 specification.
#
# pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:5
class JSON_RPC::JsonRpcError < ::StandardError
  # Initialize the error using a symbol key, with optional custom message and data.
  #
  # @param symbol [Symbol] The error symbol.
  # @param message [String, nil] Optional custom message.
  # @param data [Object, nil] Optional custom data.
  #
  # pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:74
  def initialize(symbol, message: T.unsafe(nil), data: T.unsafe(nil)); end

  # For ActiveSupport::JSON
  #
  # pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:91
  def as_json(*_arg0); end

  # @return [Integer] The error code.
  # @return [Object] The error data.
  #
  # pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:37
  def code; end

  # @return [Integer] The error code.
  # @return [Object] The error data.
  #
  # pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:37
  def data; end

  # Returns a hash formatted for a JSON-RPC error response object (the value of the 'error' key).
  #
  # @return [Hash] The error hash.
  #
  # pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:84
  def to_h; end

  class << self
    # Retrieve error details by symbol.
    #
    # @param symbol [Symbol] The error symbol.
    # @raise [ArgumentError] if the error code is unknown.
    # @return [Hash] The error details.
    #
    # pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:44
    def [](symbol); end

    # Build an error hash, allowing custom message or data to override defaults.
    #
    # @param symbol [Symbol] The error symbol.
    # @param message [String, nil] Optional custom message.
    # @param data [Object, nil] Optional custom data.
    # @return [Hash] The error hash.
    #
    # pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:62
    def build(symbol, message: T.unsafe(nil), data: T.unsafe(nil)); end

    # Retrieve error details by code.
    #
    # @param code [Integer] The error code.
    # @return [Hash, nil] The error details hash if found, otherwise nil.
    #
    # pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:52
    def find_by_code(code); end
  end
end

# Define the standard JSON-RPC 2.0 error codes
#
# pkg:gem/jsonrpc-rails#lib/json_rpc/json_rpc_error.rb:7
JSON_RPC::JsonRpcError::ERROR_CODES = T.let(T.unsafe(nil), Hash)

# Represents a JSON-RPC notification.
#
# pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:5
class JSON_RPC::Notification < ::Data
  # pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:10
  def initialize(method:, params: T.unsafe(nil)); end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:32
  def as_json(*_arg0); end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:5
  def method; end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:5
  def params; end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:22
  def to_h; end

  class << self
    # pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:5
    def [](*_arg0); end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:15
    def from_h(h); end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:5
    def inspect; end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:5
    def members; end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/notification.rb:5
    def new(*_arg0); end
  end
end

# pkg:gem/jsonrpc-rails#lib/json_rpc/parser.rb:4
module JSON_RPC::Parser
  class << self
    # Convert raw JSON string into typed object(s).
    #
    # pkg:gem/jsonrpc-rails#lib/json_rpc/parser.rb:19
    def array_from_json(json); end

    # Convert one JSON-RPC hash into a typed object.
    #
    # pkg:gem/jsonrpc-rails#lib/json_rpc/parser.rb:6
    def object_from_hash(h); end
  end
end

# Represents a JSON-RPC request object.
#
# pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:5
class JSON_RPC::Request < ::Data
  # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:12
  def initialize(id:, method:, params: T.unsafe(nil)); end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:37
  def as_json(*_arg0); end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:5
  def id; end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:5
  def method; end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:5
  def params; end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:26
  def to_h; end

  private

  # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:46
  def validate_id_type(id); end

  class << self
    # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:5
    def [](*_arg0); end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:19
    def from_h(h); end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:5
    def inspect; end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:5
    def members; end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/request.rb:5
    def new(*_arg0); end
  end
end

# Represents a JSON-RPC response object.
#
# pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:5
class JSON_RPC::Response < ::Data
  # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:12
  def initialize(id:, **kwargs); end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:47
  def as_json(*_arg0); end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:5
  def error; end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:5
  def id; end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:5
  def result; end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:36
  def to_h; end

  private

  # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:75
  def process_error(error_input); end

  # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:59
  def validate_response(id, has_result, has_error, result, error_input); end

  class << self
    # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:5
    def [](*_arg0); end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:26
    def from_h(h); end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:5
    def inspect; end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:5
    def members; end

    # pkg:gem/jsonrpc-rails#lib/json_rpc/response.rb:5
    def new(*_arg0); end
  end
end
