# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `lint_roller` gem.
# Please instead update this file by running `bin/tapioca gem lint_roller`.


module LintRoller; end

class LintRoller::Context < ::Struct
  def engine; end
  def engine=(_); end
  def engine_version; end
  def engine_version=(_); end
  def rule_format; end
  def rule_format=(_); end
  def runner; end
  def runner=(_); end
  def runner_version; end
  def runner_version=(_); end
  def target_ruby_version; end
  def target_ruby_version=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end
