# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `money-rails` gem.
# Please instead update this file by running `bin/tapioca gem money-rails`.


# pkg:gem/money-rails#lib/money-rails/money.rb:4
class Money
  # This is expected to be called by ActiveSupport when calling as_json an Money object
  #
  # pkg:gem/money-rails#lib/money-rails/money.rb:26
  def to_hash; end

  class << self
    # pkg:gem/money-rails#lib/money-rails/money.rb:8
    def default_formatting_rules; end

    # pkg:gem/money-rails#lib/money-rails/money.rb:6
    def orig_default_formatting_rules; end
  end
end

# pkg:gem/money-rails#lib/money-rails/configuration.rb:5
module MoneyRails
  extend ::MoneyRails::Configuration
end

# pkg:gem/money-rails#lib/money-rails/helpers/action_view_extension.rb:2
module MoneyRails::ActionViewExtension
  # pkg:gem/money-rails#lib/money-rails/helpers/action_view_extension.rb:3
  def currency_symbol(currency = T.unsafe(nil)); end

  # pkg:gem/money-rails#lib/money-rails/helpers/action_view_extension.rb:7
  def humanized_money(value, options = T.unsafe(nil)); end

  # pkg:gem/money-rails#lib/money-rails/helpers/action_view_extension.rb:28
  def humanized_money_with_symbol(value, options = T.unsafe(nil)); end

  # pkg:gem/money-rails#lib/money-rails/helpers/action_view_extension.rb:51
  def money_only_cents(value); end

  # pkg:gem/money-rails#lib/money-rails/helpers/action_view_extension.rb:32
  def money_without_cents(value, options = T.unsafe(nil)); end

  # pkg:gem/money-rails#lib/money-rails/helpers/action_view_extension.rb:47
  def money_without_cents_and_with_symbol(value); end
end

# pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:6
module MoneyRails::ActiveRecord; end

# pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:7
module MoneyRails::ActiveRecord::Monetizable
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::MoneyRails::ActiveRecord::Monetizable::ClassMethods

  # pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:297
  def currency_for(name, instance_currency_name, field_currency_name); end

  # pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:191
  def read_monetized(name, subunit_name, options = T.unsafe(nil), *args, **kwargs); end

  # pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:241
  def write_monetized(name, subunit_name, value, validation_enabled, instance_currency_name, options); end
end

# pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:11
module MoneyRails::ActiveRecord::Monetizable::ClassMethods
  # pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:24
  def monetize(*fields); end

  # pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:14
  def monetized_attributes; end

  # pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:164
  def register_currency(currency_name); end

  private

  # pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:180
  def track_monetized_attribute(name, value); end
end

# pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:12
MoneyRails::ActiveRecord::Monetizable::ClassMethods::MODULE_NAME = T.let(T.unsafe(nil), Symbol)

# pkg:gem/money-rails#lib/money-rails/active_record/monetizable.rb:8
class MoneyRails::ActiveRecord::Monetizable::ReadOnlyCurrencyException < ::MoneyRails::Error; end

# MoneyRails configuration module.
# This is extended by MoneyRails to provide configuration settings.
#
# pkg:gem/money-rails#lib/money-rails/configuration.rb:9
module MoneyRails::Configuration
  # pkg:gem/money-rails#lib/money-rails/configuration.rb:64
  def add_rate(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:71
  def amount_column; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:71
  def amount_column=(val); end

  # Start a MoneyRails configuration block in an initializer.
  #
  # example: Provide a default currency for the application
  #   MoneyRails.configure do |config|
  #     config.default_currency = :eur
  #   end
  #
  # pkg:gem/money-rails#lib/money-rails/configuration.rb:16
  def configure; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:74
  def currency_column; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:74
  def currency_column=(val); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:61
  def default_bank(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:61
  def default_bank=(arg); end

  # Configuration parameters
  #
  # pkg:gem/money-rails#lib/money-rails/configuration.rb:22
  def default_currency; end

  # Set default currency of money library
  #
  # pkg:gem/money-rails#lib/money-rails/configuration.rb:27
  def default_currency=(currency_name); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:87
  def default_format; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:87
  def default_format=(val); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:67
  def include_validations; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:67
  def include_validations=(val); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:61
  def locale_backend(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:61
  def locale_backend=(arg); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:78
  def no_cents_if_whole; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:78
  def no_cents_if_whole=(val); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:96
  def preserve_user_input; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:96
  def preserve_user_input=(val); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:92
  def raise_error_on_money_parsing; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:92
  def raise_error_on_money_parsing=(val); end

  # Register a custom currency
  #
  # pkg:gem/money-rails#lib/money-rails/configuration.rb:33
  def register_currency=(currency_options); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:42
  def rounding_mode=(mode); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:37
  def set_currency_column_for_default_currency!; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:84
  def sign_before_symbol; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:84
  def sign_before_symbol=(val); end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:81
  def symbol; end

  # pkg:gem/money-rails#lib/money-rails/configuration.rb:81
  def symbol=(val); end

  class << self
    # pkg:gem/money-rails#lib/money-rails/configuration.rb:71
    def amount_column; end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:71
    def amount_column=(val); end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:74
    def currency_column; end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:74
    def currency_column=(val); end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:87
    def default_format; end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:87
    def default_format=(val); end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:67
    def include_validations; end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:67
    def include_validations=(val); end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:78
    def no_cents_if_whole; end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:78
    def no_cents_if_whole=(val); end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:96
    def preserve_user_input; end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:96
    def preserve_user_input=(val); end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:92
    def raise_error_on_money_parsing; end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:92
    def raise_error_on_money_parsing=(val); end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:84
    def sign_before_symbol; end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:84
    def sign_before_symbol=(val); end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:81
    def symbol; end

    # pkg:gem/money-rails#lib/money-rails/configuration.rb:81
    def symbol=(val); end
  end
end

# pkg:gem/money-rails#lib/money-rails/engine.rb:2
class MoneyRails::Engine < ::Rails::Engine; end

# pkg:gem/money-rails#lib/money-rails/errors.rb:2
class MoneyRails::Error < ::StandardError; end

# pkg:gem/money-rails#lib/money-rails/hooks.rb:2
class MoneyRails::Hooks
  class << self
    # pkg:gem/money-rails#lib/money-rails/hooks.rb:5
    def init; end
  end
end

# pkg:gem/money-rails#lib/money-rails/hooks.rb:3
MoneyRails::Hooks::PG_ADAPTERS = T.let(T.unsafe(nil), Array)

# pkg:gem/money-rails#lib/money-rails/railtie.rb:2
class MoneyRails::Railtie < ::Rails::Railtie; end

# pkg:gem/money-rails#lib/money-rails/version.rb:4
MoneyRails::VERSION = T.let(T.unsafe(nil), String)
