# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `monetize` gem.
# Please instead update this file by running `bin/tapioca gem monetize`.


# pkg:gem/monetize#lib/monetize/core_extensions/hash.rb:1
class Hash
  include ::Enumerable
  include ::ActiveSupport::DeepMergeable

  # pkg:gem/monetize#lib/monetize/core_extensions/hash.rb:2
  def to_money(currency = T.unsafe(nil)); end
end

# pkg:gem/monetize#lib/monetize/errors.rb:1
module Monetize
  class << self
    # @attr_accessor [true, false] assume_from_symbol Use this to enable the
    #   ability to assume the currency from a passed symbol
    #
    # pkg:gem/monetize#lib/monetize.rb:13
    def assume_from_symbol; end

    # @attr_accessor [true, false] assume_from_symbol Use this to enable the
    #   ability to assume the currency from a passed symbol
    #
    # pkg:gem/monetize#lib/monetize.rb:13
    def assume_from_symbol=(_arg0); end

    # Monetize uses the delimiters set in the currency to separate integers from
    # decimals, and to ignore thousands separators. In some corner cases,
    # though, it will try to determine the correct separator by itself. Set this
    # to true to enforce the delimiters set in the currency all the time.
    #
    # pkg:gem/monetize#lib/monetize.rb:19
    def enforce_currency_delimiters; end

    # Monetize uses the delimiters set in the currency to separate integers from
    # decimals, and to ignore thousands separators. In some corner cases,
    # though, it will try to determine the correct separator by itself. Set this
    # to true to enforce the delimiters set in the currency all the time.
    #
    # pkg:gem/monetize#lib/monetize.rb:19
    def enforce_currency_delimiters=(_arg0); end

    # Where this set to true, the behavior for parsing thousands separators is changed to
    # expect that eg. €10.000 is EUR 10 000 and not EUR 10.000 - it's incredibly rare when parsing
    # human text that we're dealing with fractions of cents.
    #
    # pkg:gem/monetize#lib/monetize.rb:25
    def expect_whole_subunits; end

    # Where this set to true, the behavior for parsing thousands separators is changed to
    # expect that eg. €10.000 is EUR 10 000 and not EUR 10.000 - it's incredibly rare when parsing
    # human text that we're dealing with fractions of cents.
    #
    # pkg:gem/monetize#lib/monetize.rb:25
    def expect_whole_subunits=(_arg0); end

    # pkg:gem/monetize#lib/monetize.rb:63
    def from_bigdecimal(value, currency = T.unsafe(nil)); end

    # pkg:gem/monetize#lib/monetize.rb:54
    def from_fixnum(value, currency = T.unsafe(nil)); end

    # pkg:gem/monetize#lib/monetize.rb:59
    def from_float(value, currency = T.unsafe(nil)); end

    # pkg:gem/monetize#lib/monetize.rb:57
    def from_integer(value, currency = T.unsafe(nil)); end

    # pkg:gem/monetize#lib/monetize.rb:67
    def from_numeric(value, currency = T.unsafe(nil)); end

    # pkg:gem/monetize#lib/monetize.rb:49
    def from_string(value, currency = T.unsafe(nil)); end

    # pkg:gem/monetize#lib/monetize.rb:27
    def parse(input, currency = T.unsafe(nil), options = T.unsafe(nil)); end

    # pkg:gem/monetize#lib/monetize.rb:33
    def parse!(input, currency = T.unsafe(nil), options = T.unsafe(nil)); end

    # pkg:gem/monetize#lib/monetize.rb:45
    def parse_collection(input, currency = T.unsafe(nil), options = T.unsafe(nil)); end
  end
end

# pkg:gem/monetize#lib/monetize/errors.rb:5
class Monetize::ArgumentError < ::Monetize::Error; end

# pkg:gem/monetize#lib/monetize/collection.rb:4
class Monetize::Collection
  include ::Enumerable
  extend ::Forwardable

  # pkg:gem/monetize#lib/monetize/collection.rb:15
  def initialize(input, currency = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/monetize#lib/monetize/collection.rb:7
  def [](*_arg0, **_arg1, &_arg2); end

  # pkg:gem/monetize#lib/monetize/collection.rb:9
  def currency; end

  # pkg:gem/monetize#lib/monetize/collection.rb:7
  def each(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/monetize#lib/monetize/collection.rb:9
  def input; end

  # pkg:gem/monetize#lib/monetize/collection.rb:7
  def last(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/monetize#lib/monetize/collection.rb:9
  def options; end

  # pkg:gem/monetize#lib/monetize/collection.rb:27
  def parse; end

  # pkg:gem/monetize#lib/monetize/collection.rb:37
  def range?; end

  private

  # pkg:gem/monetize#lib/monetize/collection.rb:46
  def split_list; end

  # pkg:gem/monetize#lib/monetize/collection.rb:50
  def split_range; end

  class << self
    # pkg:gem/monetize#lib/monetize/collection.rb:11
    def parse(input, currency = T.unsafe(nil), options = T.unsafe(nil)); end
  end
end

# pkg:gem/monetize#lib/monetize/collection.rb:43
Monetize::Collection::LIST_SPLIT = T.let(T.unsafe(nil), Regexp)

# pkg:gem/monetize#lib/monetize/collection.rb:44
Monetize::Collection::RANGE_SPLIT = T.let(T.unsafe(nil), Regexp)

# pkg:gem/monetize#lib/monetize/errors.rb:2
class Monetize::Error < ::StandardError; end

# pkg:gem/monetize#lib/monetize/errors.rb:4
class Monetize::ParseError < ::Monetize::Error; end

# pkg:gem/monetize#lib/monetize/parser.rb:2
class Monetize::Parser
  # pkg:gem/monetize#lib/monetize/parser.rb:39
  def initialize(input, fallback_currency = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/monetize#lib/monetize/parser.rb:45
  def parse; end

  private

  # pkg:gem/monetize#lib/monetize/parser.rb:94
  def apply_multiplier(multiplier_exp, amount); end

  # pkg:gem/monetize#lib/monetize/parser.rb:98
  def apply_sign(negative, amount); end

  # pkg:gem/monetize#lib/monetize/parser.rb:86
  def assume_from_symbol?; end

  # pkg:gem/monetize#lib/monetize/parser.rb:102
  def compute_currency; end

  # pkg:gem/monetize#lib/monetize/parser.rb:90
  def expect_whole_subunits?; end

  # pkg:gem/monetize#lib/monetize/parser.rb:107
  def extract_major_minor(num, currency); end

  # pkg:gem/monetize#lib/monetize/parser.rb:127
  def extract_major_minor_with_single_delimiter(num, currency, delimiter); end

  # pkg:gem/monetize#lib/monetize/parser.rb:146
  def extract_major_minor_with_tentative_delimiter(num, delimiter); end

  # pkg:gem/monetize#lib/monetize/parser.rb:167
  def extract_multiplier; end

  # pkg:gem/monetize#lib/monetize/parser.rb:176
  def extract_sign(input); end

  # pkg:gem/monetize#lib/monetize/parser.rb:73
  def fallback_currency; end

  # pkg:gem/monetize#lib/monetize/parser.rb:73
  def input; end

  # pkg:gem/monetize#lib/monetize/parser.rb:123
  def minor_has_correct_dp_for_currency_subunit?(minor, currency); end

  # pkg:gem/monetize#lib/monetize/parser.rb:73
  def options; end

  # pkg:gem/monetize#lib/monetize/parser.rb:75
  def parse_currency; end

  # pkg:gem/monetize#lib/monetize/parser.rb:182
  def split_major_minor(num, delimiter); end

  # pkg:gem/monetize#lib/monetize/parser.rb:67
  def to_big_decimal(value); end
end

# pkg:gem/monetize#lib/monetize/parser.rb:3
Monetize::Parser::CURRENCY_SYMBOLS = T.let(T.unsafe(nil), Hash)

# pkg:gem/monetize#lib/monetize/parser.rb:32
Monetize::Parser::CURRENCY_SYMBOL_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/monetize#lib/monetize/parser.rb:37
Monetize::Parser::DEFAULT_DECIMAL_MARK = T.let(T.unsafe(nil), String)

# pkg:gem/monetize#lib/monetize/parser.rb:35
Monetize::Parser::MULTIPLIER_REGEXP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/monetize#lib/monetize/parser.rb:33
Monetize::Parser::MULTIPLIER_SUFFIXES = T.let(T.unsafe(nil), Hash)

# pkg:gem/monetize#lib/monetize/version.rb:2
Monetize::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/monetize#lib/monetize/core_extensions/nil_class.rb:1
class NilClass
  # pkg:gem/monetize#lib/monetize/core_extensions/nil_class.rb:2
  def to_money(currency = T.unsafe(nil)); end
end

# pkg:gem/monetize#lib/monetize/core_extensions/numeric.rb:1
class Numeric
  include ::Comparable

  # pkg:gem/monetize#lib/monetize/core_extensions/numeric.rb:2
  def to_money(currency = T.unsafe(nil)); end
end

# pkg:gem/monetize#lib/monetize/core_extensions/string.rb:1
class String
  include ::Comparable

  # pkg:gem/monetize#lib/monetize/core_extensions/string.rb:6
  def to_currency; end

  # pkg:gem/monetize#lib/monetize/core_extensions/string.rb:2
  def to_money(currency = T.unsafe(nil)); end
end

# pkg:gem/monetize#lib/monetize/core_extensions/symbol.rb:1
class Symbol
  include ::Comparable

  # pkg:gem/monetize#lib/monetize/core_extensions/symbol.rb:2
  def to_currency; end
end
