# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `noticed` gem.
# Please instead update this file by running `bin/tapioca gem noticed`.


module Noticed
  include ::ActiveSupport::Deprecation::DeprecatedConstantAccessor

  def parent_class; end
  def parent_class=(val); end

  class << self
    def deprecator; end
    def parent_class; end
    def parent_class=(val); end
    def railtie_helpers_paths; end
    def railtie_namespace; end
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end
    def table_name_prefix; end
    def use_relative_model_naming?; end
  end
end

module Noticed::ApiClient
  extend ::ActiveSupport::Concern

  def post_request(url, args = T.unsafe(nil)); end
end

class Noticed::ApplicationJob < ::ActiveJob::Base
  class << self
    def rescue_handlers; end
  end
end

class Noticed::ApplicationRecord < ::ActiveRecord::Base
  include ::Noticed::ApplicationRecord::GeneratedAttributeMethods
  include ::Noticed::ApplicationRecord::GeneratedAssociationMethods
  include ::Kaminari::ActiveRecordModelExtension
  include ::Kaminari::ConfigurationMethods
  extend ::Kaminari::ConfigurationMethods::ClassMethods

  class << self
    def _validators; end
    def defined_enums; end
    def page(num = T.unsafe(nil)); end
    def table_name_prefix; end
  end
end

module Noticed::ApplicationRecord::GeneratedAssociationMethods; end
module Noticed::ApplicationRecord::GeneratedAttributeMethods; end

class Noticed::BulkDeliveryMethod < ::Noticed::ApplicationJob
  include ::Noticed::ApiClient
  include ::Noticed::RequiredOptions
  extend ::Noticed::RequiredOptions::ClassMethods
  extend ::ActiveModel::Callbacks

  def _deliver_callbacks; end
  def _run_deliver_callbacks(&block); end
  def config; end
  def deliver; end
  def evaluate_option(name); end
  def event; end
  def fetch_constant(name); end
  def logger; end
  def logger=(_arg0); end
  def logger?; end
  def perform(delivery_method_name, event, recipient: T.unsafe(nil), params: T.unsafe(nil), overrides: T.unsafe(nil)); end
  def required_option_names; end
  def required_option_names?; end

  class << self
    def __callbacks; end
    def _deliver_callbacks; end
    def _deliver_callbacks=(value); end
    def after_deliver(*args, **options, &block); end
    def around_deliver(*args, **options, &block); end
    def before_deliver(*args, **options, &block); end
    def logger; end
    def logger=(value); end
    def logger?; end
    def required_option_names; end
    def required_option_names=(value); end
    def required_option_names?; end
  end
end

module Noticed::BulkDeliveryMethods; end

class Noticed::BulkDeliveryMethods::Bluesky < ::Noticed::BulkDeliveryMethod
  def deliver; end
  def host; end
  def identifier; end
  def start_session; end
  def token; end

  class << self
    def required_option_names; end
  end
end

class Noticed::BulkDeliveryMethods::Discord < ::Noticed::BulkDeliveryMethod
  def deliver; end

  class << self
    def required_option_names; end
  end
end

class Noticed::BulkDeliveryMethods::Slack < ::Noticed::BulkDeliveryMethod
  def deliver; end
  def raise_if_not_ok?; end
  def success?(response); end
  def url; end

  class << self
    def required_option_names; end
  end
end

Noticed::BulkDeliveryMethods::Slack::DEFAULT_URL = T.let(T.unsafe(nil), String)

class Noticed::BulkDeliveryMethods::Test < ::Noticed::BulkDeliveryMethod
  def deliver; end
  def delivered; end
  def delivered=(_arg0); end
  def delivered?; end

  class << self
    def delivered; end
    def delivered=(value); end
    def delivered?; end
    def required_option_names; end
  end
end

class Noticed::BulkDeliveryMethods::Webhook < ::Noticed::BulkDeliveryMethod
  def deliver; end

  class << self
    def required_option_names; end
  end
end

class Noticed::Coder
  class << self
    def dump(data); end
    def load(data); end
  end
end

module Noticed::Deliverable
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::Noticed::Deliverable::ClassMethods

  def deliver(recipients = T.unsafe(nil), enqueue_job: T.unsafe(nil), **options); end
  def deliver_later(recipients = T.unsafe(nil), enqueue_job: T.unsafe(nil), **options); end
  def deserialize_error?; end
  def evaluate_recipients; end
  def recipient_attributes_for(recipient); end
  def validate!; end
  def validate_delivery_methods!; end
  def validate_params!; end

  module GeneratedClassMethods
    def _recipients; end
    def _recipients=(value); end
    def _recipients?; end
    def bulk_delivery_methods; end
    def bulk_delivery_methods=(value); end
    def bulk_delivery_methods?; end
    def delivery_methods; end
    def delivery_methods=(value); end
    def delivery_methods?; end
    def required_param_names; end
    def required_param_names=(value); end
    def required_param_names?; end
  end

  module GeneratedInstanceMethods
    def _recipients; end
    def _recipients?; end
    def bulk_delivery_methods; end
    def bulk_delivery_methods?; end
    def delivery_methods; end
    def delivery_methods?; end
    def required_param_names; end
    def required_param_names?; end
  end
end

module Noticed::Deliverable::ClassMethods
  def bulk_deliver_by(name, options = T.unsafe(nil)); end
  def deliver(recipients = T.unsafe(nil), **options); end
  def deliver_by(name, options = T.unsafe(nil)); end
  def deliver_later(recipients = T.unsafe(nil), **options); end
  def inherited(base); end
  def param(*names); end
  def params(*names); end
  def recipients(option = T.unsafe(nil), &block); end
  def required_param(*names); end
  def required_params(*names); end
  def with(params); end
end

class Noticed::Deliverable::DeliverBy
  def initialize(name, config, bulk: T.unsafe(nil)); end

  def bulk; end
  def config; end
  def constant; end
  def ephemeral_perform_later(notifier, recipient, params, options = T.unsafe(nil)); end
  def evaluate_option(name, context); end
  def name; end
  def perform?(notification); end
  def perform_later(event_or_notification, options = T.unsafe(nil)); end
  def validate!; end

  private

  def computed_options(options, recipient); end
end

class Noticed::DeliveryMethod < ::Noticed::ApplicationJob
  include ::Noticed::ApiClient
  include ::Noticed::RequiredOptions
  extend ::Noticed::RequiredOptions::ClassMethods
  extend ::ActiveModel::Callbacks

  def _deliver_callbacks; end
  def _run_deliver_callbacks(&block); end
  def config; end
  def deliver; end
  def evaluate_option(name); end
  def event; end
  def fetch_constant(name); end
  def logger; end
  def logger=(_arg0); end
  def logger?; end
  def notification; end
  def params(*_arg0, **_arg1, &_arg2); end
  def perform(delivery_method_name, notification, recipient: T.unsafe(nil), params: T.unsafe(nil), overrides: T.unsafe(nil)); end
  def recipient(*_arg0, **_arg1, &_arg2); end
  def record(*_arg0, **_arg1, &_arg2); end
  def required_option_names; end
  def required_option_names?; end

  class << self
    def __callbacks; end
    def _deliver_callbacks; end
    def _deliver_callbacks=(value); end
    def after_deliver(*args, **options, &block); end
    def around_deliver(*args, **options, &block); end
    def before_deliver(*args, **options, &block); end
    def logger; end
    def logger=(value); end
    def logger?; end
    def required_option_names; end
    def required_option_names=(value); end
    def required_option_names?; end
  end
end

module Noticed::DeliveryMethods
  include ::ActiveSupport::Deprecation::DeprecatedConstantAccessor
end

class Noticed::DeliveryMethods::ActionCable < ::Noticed::DeliveryMethod
  def channel; end
  def deliver; end
  def stream; end

  class << self
    def required_option_names; end
  end
end

class Noticed::DeliveryMethods::ActionPushNative < ::Noticed::DeliveryMethod
  def deliver; end
  def notification_class; end

  class << self
    def required_option_names; end
  end
end

class Noticed::DeliveryMethods::Discord < ::Noticed::BulkDeliveryMethod
  def deliver; end

  class << self
    def required_option_names; end
  end
end

class Noticed::DeliveryMethods::Email < ::Noticed::DeliveryMethod
  def deliver; end
  def params; end

  class << self
    def required_option_names; end
  end
end

class Noticed::DeliveryMethods::MicrosoftTeams < ::Noticed::DeliveryMethod
  def deliver; end
  def url; end

  class << self
    def required_option_names; end
  end
end

class Noticed::DeliveryMethods::Slack < ::Noticed::DeliveryMethod
  def deliver; end
  def raise_if_not_ok?; end
  def success?(response); end
  def url; end

  class << self
    def required_option_names; end
  end
end

Noticed::DeliveryMethods::Slack::DEFAULT_URL = T.let(T.unsafe(nil), String)

class Noticed::DeliveryMethods::Test < ::Noticed::DeliveryMethod
  def deliver; end
  def delivered; end
  def delivered=(_arg0); end
  def delivered?; end

  class << self
    def delivered; end
    def delivered=(value); end
    def delivered?; end
    def required_option_names; end
  end
end

class Noticed::DeliveryMethods::TwilioMessaging < ::Noticed::DeliveryMethod
  def account_sid; end
  def auth_token; end
  def credentials; end
  def deliver; end
  def json; end
  def phone_number; end
  def url; end

  class << self
    def required_option_names; end
  end
end

class Noticed::DeliveryMethods::VonageSms < ::Noticed::DeliveryMethod
  def deliver; end
  def url; end

  class << self
    def required_option_names; end
  end
end

Noticed::DeliveryMethods::VonageSms::DEFAULT_URL = T.let(T.unsafe(nil), String)

class Noticed::DeliveryMethods::Webhook < ::Noticed::DeliveryMethod
  def deliver; end

  class << self
    def required_option_names; end
  end
end

class Noticed::Engine < ::Rails::Engine; end

class Noticed::EventJob < ::Noticed::ApplicationJob
  def perform(event); end
end

module Noticed::HasNotifications
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Noticed::HasNotifications::ClassMethods

  def current_adapter; end
end

module Noticed::HasNotifications::ClassMethods
  def has_noticed_notifications(param_name: T.unsafe(nil), **options); end
end

module Noticed::NotificationMethods
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Noticed::NotificationMethods::ClassMethods
end

module Noticed::NotificationMethods::ClassMethods
  def inherited(notifier); end
  def notification_methods(&block); end
end

module Noticed::Readable
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Noticed::Readable::ClassMethods

  def mark_as_read; end
  def mark_as_read!; end
  def mark_as_seen; end
  def mark_as_seen!; end
  def mark_as_unread; end
  def mark_as_unread!; end
  def mark_as_unseen; end
  def mark_as_unseen!; end
  def read?; end
  def seen?; end
  def unread?; end
  def unseen?; end
end

module Noticed::Readable::ClassMethods
  def mark_as_read(**kwargs); end
  def mark_as_read_and_seen(**kwargs); end
  def mark_as_seen(**kwargs); end
  def mark_as_unread(**kwargs); end
  def mark_as_unread_and_unseen(**kwargs); end
  def mark_as_unseen(**kwargs); end
end

module Noticed::RequiredOptions
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::Noticed::RequiredOptions::ClassMethods

  module GeneratedClassMethods
    def required_option_names; end
    def required_option_names=(value); end
    def required_option_names?; end
  end

  module GeneratedInstanceMethods
    def required_option_names; end
    def required_option_names?; end
  end
end

module Noticed::RequiredOptions::ClassMethods
  def inherited(base); end
  def required_option(*names); end
  def required_options(*names); end
end

class Noticed::ResponseUnsuccessful < ::StandardError
  def initialize(response, url, args); end

  def response; end
end

module Noticed::Translation
  extend ::ActiveSupport::Concern

  def class_scope; end
  def i18n_scope; end
  def scope_translation_key(key); end
  def t(key, **options); end
  def translate(key, **options); end
end

Noticed::VERSION = T.let(T.unsafe(nil), String)
class Noticed::ValidationError < ::StandardError; end
