# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rack-session` gem.
# Please instead update this file by running `bin/tapioca gem rack-session`.


# Released under the MIT License.
# Copyright, 2022-2023, by Samuel Williams.
# Copyright, 2022, by Jeremy Evans.
# Released under the MIT License.
# Copyright, 2022-2023, by Samuel Williams.
# Copyright, 2022, by Jeremy Evans.
# Released under the MIT License.
# Copyright, 2022-2023, by Samuel Williams.
#
# pkg:gem/rack-session#lib/rack/session/constants.rb:7
module Rack; end

# pkg:gem/rack-session#lib/rack/session/constants.rb:8
module Rack::Session; end

# pkg:gem/rack-session#lib/rack/session/abstract/id.rb:47
module Rack::Session::Abstract; end

# pkg:gem/rack-session#lib/rack/session/abstract/id.rb:499
class Rack::Session::Abstract::ID < ::Rack::Session::Abstract::Persisted
  # All thread safety and session destroy procedures should occur here.
  # Should return a new session id or nil if options[:drop]
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:529
  def delete_session(req, sid, options); end

  # All thread safety and session retrieval procedures should occur here.
  # Should return [session_id, session].
  # If nil is provided as the session id, generation of a new valid id
  # should occur within.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:514
  def find_session(req, sid); end

  # All thread safety and session storage procedures should occur here.
  # Must return the session id if the session was saved successfully, or
  # false if the session could not be saved.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:522
  def write_session(req, sid, session, options); end

  class << self
    # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:500
    def inherited(klass); end
  end
end

# ID sets up a basic framework for implementing an id based sessioning
# service. Cookies sent to the client for maintaining sessions will only
# contain an id reference. Only #find_session, #write_session and
# #delete_session are required to be overwritten.
#
# All parameters are optional.
# * :key determines the name of the cookie, by default it is
#   'rack.session'
# * :path, :domain, :expire_after, :secure, :httponly, :partitioned and :same_site set
#   the related cookie options as by Rack::Response#set_cookie
# * :skip will not a set a cookie in the response nor update the session state
# * :defer will not set a cookie in the response but still update the session
#   state if it is used with a backend
# * :renew (implementation dependent) will prompt the generation of a new
#   session id, and migration of data to be referenced at the new id. If
#   :defer is set, it will be overridden and the cookie will be set.
# * :sidbits sets the number of bits in length that a generated session
#   id will be.
#
# These options can be set on a per request basis, at the location of
# <tt>env['rack.session.options']</tt>. Additionally the id of the
# session can be found within the options hash at the key :id. It is
# highly not recommended to change its value.
#
# Is Rack::Utils::Context compatible.
#
# Not included by default; you must require 'rack/session/abstract/id'
# to use.
#
# pkg:gem/rack-session#lib/rack/session/abstract/id.rb:239
class Rack::Session::Abstract::Persisted
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:257
  def initialize(app, options = T.unsafe(nil)); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:267
  def call(env); end

  # Acquires the session from the environment and the session id from
  # the session options and passes them to #write_session. If successful
  # and the :defer option is not true, a cookie will be added to the
  # response with the session's id.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:381
  def commit_session(req, res); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:271
  def context(env, app = T.unsafe(nil)); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:255
  def default_options; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:255
  def key; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:255
  def same_site; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:255
  def sid_secure; end

  private

  # Session should be committed if it was loaded, any of specific options like :renew, :drop
  # or :expire_after was given and the security permissions match. Skips if skip is given.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:350
  def commit_session?(req, session, options); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:416
  def cookie_value(data); end

  # Returns the current session id from the SessionHash.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:336
  def current_session_id(req); end

  # All thread safety and session destroy procedures should occur here.
  # Should return a new session id or nil if options[:drop]
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:455
  def delete_session(req, sid, options); end

  # Extract session id from request object.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:328
  def extract_session_id(request); end

  # All thread safety and session retrieval procedures should occur here.
  # Should return [session_id, session].
  # If nil is provided as the session id, generation of a new valid id
  # should occur within.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:440
  def find_session(env, sid); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:367
  def force_options?(options); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:363
  def forced_session_update?(session, options); end

  # Generate a new session id using Ruby #rand.  The size of the
  # session id is controlled by the :sidbits option.
  # Monkey patch this to use custom methods for session id generation.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:296
  def generate_sid(secure = T.unsafe(nil)); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:286
  def initialize_sid; end

  # Extracts the session id from provided cookies and passes it and the
  # environment to #find_session.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:320
  def load_session(req); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:359
  def loaded_session?(session); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:282
  def make_request(env); end

  # Sets the lazy session at 'rack.session' and places options and session
  # metadata into 'rack.session.options'.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:309
  def prepare_session(req); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:371
  def security_matches?(request, options); end

  # Allow subclasses to prepare_session for different Session classes
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:431
  def session_class; end

  # Check if the session exists or not.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:342
  def session_exists?(req); end

  # Sets the cookie back to the client with session id. We skip the cookie
  # setting if the value didn't change (sid is the same) or expires was given.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:423
  def set_cookie(request, response, cookie); end

  # All thread safety and session storage procedures should occur here.
  # Must return the session id if the session was saved successfully, or
  # false if the session could not be saved.
  #
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:448
  def write_session(req, sid, session, options); end
end

# pkg:gem/rack-session#lib/rack/session/abstract/id.rb:240
Rack::Session::Abstract::Persisted::DEFAULT_OPTIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack-session#lib/rack/session/abstract/id.rb:460
class Rack::Session::Abstract::PersistedSecure < ::Rack::Session::Abstract::Persisted
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:483
  def extract_session_id(*_arg0); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:477
  def generate_sid(*_arg0); end

  private

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:494
  def cookie_value(data); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:490
  def session_class; end
end

# pkg:gem/rack-session#lib/rack/session/abstract/id.rb:461
class Rack::Session::Abstract::PersistedSecure::SecureSessionHash < ::Rack::Session::Abstract::SessionHash
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:462
  def [](key); end
end

# SessionHash is responsible to lazily load the session from store.
#
# pkg:gem/rack-session#lib/rack/session/abstract/id.rb:50
class Rack::Session::Abstract::SessionHash
  include ::Enumerable

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:68
  def initialize(store, req); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:88
  def [](key); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:114
  def []=(key, value); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:120
  def clear; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:146
  def delete(key); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:125
  def destroy; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:93
  def dig(key, *keys); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:83
  def each(&block); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:169
  def empty?; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:159
  def exists?; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:98
  def fetch(key, default = T.unsafe(nil), &block); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:107
  def has_key?(key); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:74
  def id; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:52
  def id=(_arg0); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:112
  def include?(key); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:151
  def inspect; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:111
  def key?(key); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:174
  def keys; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:165
  def loaded?; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:139
  def merge!(hash); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:79
  def options; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:141
  def replace(hash); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:118
  def store(key, value); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:130
  def to_hash; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:135
  def update(hash); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:179
  def values; end

  private

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:194
  def load!; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:186
  def load_for_read!; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:190
  def load_for_write!; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:200
  def stringify_keys(other); end

  class << self
    # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:56
    def find(req); end

    # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:60
    def set(req, session); end

    # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:64
    def set_options(req, options); end
  end
end

# pkg:gem/rack-session#lib/rack/session/abstract/id.rb:54
Rack::Session::Abstract::SessionHash::Unspecified = T.let(T.unsafe(nil), Object)

# pkg:gem/rack-session#lib/rack/session/constants.rb:9
Rack::Session::RACK_SESSION = T.let(T.unsafe(nil), String)

# pkg:gem/rack-session#lib/rack/session/constants.rb:10
Rack::Session::RACK_SESSION_OPTIONS = T.let(T.unsafe(nil), String)

# pkg:gem/rack-session#lib/rack/session/constants.rb:11
Rack::Session::RACK_SESSION_UNPACKED_COOKIE_DATA = T.let(T.unsafe(nil), String)

# pkg:gem/rack-session#lib/rack/session/abstract/id.rb:21
class Rack::Session::SessionId
  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:26
  def initialize(public_id); end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:34
  def cookie_value; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:37
  def empty?; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:38
  def inspect; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:30
  def private_id; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:24
  def public_id; end

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:35
  def to_s; end

  private

  # pkg:gem/rack-session#lib/rack/session/abstract/id.rb:42
  def hash_sid(sid); end
end

# pkg:gem/rack-session#lib/rack/session/abstract/id.rb:22
Rack::Session::SessionId::ID_VERSION = T.let(T.unsafe(nil), Integer)
