# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `terrapin` gem.
# Please instead update this file by running `bin/tapioca gem terrapin`.


# coding: UTF-8
# coding: UTF-8
# coding: UTF-8
# coding: UTF-8
# coding: UTF-8
# coding: UTF-8
# coding: UTF-8
# coding: UTF-8
#
# pkg:gem/terrapin#lib/terrapin/os_detector.rb:3
module Terrapin; end

# pkg:gem/terrapin#lib/terrapin/command_line.rb:4
class Terrapin::CommandLine
  # pkg:gem/terrapin#lib/terrapin/command_line.rb:51
  def initialize(binary, params = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:63
  def command(interpolations = T.unsafe(nil)); end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:100
  def command_error_output; end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:96
  def command_output; end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:49
  def exit_status; end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:104
  def output; end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:69
  def run(interpolations = T.unsafe(nil)); end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:49
  def runner; end

  private

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:193
  def bit_bucket; end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:110
  def colored(text, ansi_color = T.unsafe(nil)); end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:150
  def environment; end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:146
  def execute(command); end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:158
  def interpolate(pattern, interpolations); end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:118
  def log(text); end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:130
  def os_path_prefix; end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:124
  def path_prefix; end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:154
  def runner_options; end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:178
  def shell_quote(string); end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:174
  def shell_quote_all_values(values); end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:170
  def stringify_keys(hash); end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:138
  def unix_path_prefix; end

  # pkg:gem/terrapin#lib/terrapin/command_line.rb:142
  def windows_path_prefix; end

  class << self
    # pkg:gem/terrapin#lib/terrapin/command_line.rb:18
    def environment; end

    # pkg:gem/terrapin#lib/terrapin/command_line.rb:30
    def fake!; end

    # pkg:gem/terrapin#lib/terrapin/command_line.rb:6
    def logger; end

    # pkg:gem/terrapin#lib/terrapin/command_line.rb:6
    def logger=(_arg0); end

    # pkg:gem/terrapin#lib/terrapin/command_line.rb:8
    def path; end

    # pkg:gem/terrapin#lib/terrapin/command_line.rb:12
    def path=(supplemental_path); end

    # pkg:gem/terrapin#lib/terrapin/command_line.rb:6
    def runner; end

    # pkg:gem/terrapin#lib/terrapin/command_line.rb:6
    def runner=(_arg0); end

    # pkg:gem/terrapin#lib/terrapin/command_line.rb:26
    def runner_options; end

    # pkg:gem/terrapin#lib/terrapin/command_line.rb:34
    def unfake!; end

    private

    # pkg:gem/terrapin#lib/terrapin/command_line.rb:40
    def best_runner; end
  end
end

# pkg:gem/terrapin#lib/terrapin/command_line/runners/backticks_runner.rb:7
class Terrapin::CommandLine::BackticksRunner
  # pkg:gem/terrapin#lib/terrapin/command_line/runners/backticks_runner.rb:16
  def call(command, env = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/backticks_runner.rb:12
  def supported?; end

  private

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/backticks_runner.rb:24
  def with_modified_environment(env, &block); end

  class << self
    # pkg:gem/terrapin#lib/terrapin/command_line/runners/backticks_runner.rb:8
    def supported?; end
  end
end

# pkg:gem/terrapin#lib/terrapin/command_line/runners/fake_runner.rb:5
class Terrapin::CommandLine::FakeRunner
  # pkg:gem/terrapin#lib/terrapin/command_line/runners/fake_runner.rb:16
  def initialize; end

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/fake_runner.rb:20
  def call(command, env = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/fake_runner.rb:14
  def commands; end

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/fake_runner.rb:25
  def ran?(predicate_command); end

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/fake_runner.rb:10
  def supported?; end

  class << self
    # pkg:gem/terrapin#lib/terrapin/command_line/runners/fake_runner.rb:6
    def supported?; end
  end
end

# pkg:gem/terrapin#lib/terrapin/command_line/multi_pipe.rb:3
class Terrapin::CommandLine::MultiPipe
  # pkg:gem/terrapin#lib/terrapin/command_line/multi_pipe.rb:4
  def initialize; end

  # pkg:gem/terrapin#lib/terrapin/command_line/multi_pipe.rb:13
  def output; end

  # pkg:gem/terrapin#lib/terrapin/command_line/multi_pipe.rb:9
  def pipe_options; end

  # pkg:gem/terrapin#lib/terrapin/command_line/multi_pipe.rb:17
  def read_and_then(&block); end

  private

  # pkg:gem/terrapin#lib/terrapin/command_line/multi_pipe.rb:36
  def close_read; end

  # pkg:gem/terrapin#lib/terrapin/command_line/multi_pipe.rb:26
  def close_write; end

  # pkg:gem/terrapin#lib/terrapin/command_line/multi_pipe.rb:31
  def read; end

  # pkg:gem/terrapin#lib/terrapin/command_line/multi_pipe.rb:41
  def read_stream(io); end
end

# pkg:gem/terrapin#lib/terrapin/command_line/output.rb:1
class Terrapin::CommandLine::Output
  # pkg:gem/terrapin#lib/terrapin/command_line/output.rb:2
  def initialize(output = T.unsafe(nil), error_output = T.unsafe(nil)); end

  # pkg:gem/terrapin#lib/terrapin/command_line/output.rb:7
  def error_output; end

  # pkg:gem/terrapin#lib/terrapin/command_line/output.rb:7
  def output; end

  # pkg:gem/terrapin#lib/terrapin/command_line/output.rb:9
  def to_s; end
end

# pkg:gem/terrapin#lib/terrapin/command_line/runners/popen_runner.rb:5
class Terrapin::CommandLine::PopenRunner
  # pkg:gem/terrapin#lib/terrapin/command_line/runners/popen_runner.rb:14
  def call(command, env = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/popen_runner.rb:10
  def supported?; end

  private

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/popen_runner.rb:24
  def with_modified_environment(env, &block); end

  class << self
    # pkg:gem/terrapin#lib/terrapin/command_line/runners/popen_runner.rb:6
    def supported?; end
  end
end

# pkg:gem/terrapin#lib/terrapin/command_line/runners/posix_runner.rb:5
class Terrapin::CommandLine::PosixRunner
  # pkg:gem/terrapin#lib/terrapin/command_line/runners/posix_runner.rb:20
  def call(command, env = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/posix_runner.rb:16
  def supported?; end

  private

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/posix_runner.rb:31
  def spawn(*args); end

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/posix_runner.rb:35
  def waitpid(pid); end

  class << self
    # pkg:gem/terrapin#lib/terrapin/command_line/runners/posix_runner.rb:6
    def available?; end

    # pkg:gem/terrapin#lib/terrapin/command_line/runners/posix_runner.rb:12
    def supported?; end

    private

    # pkg:gem/terrapin#lib/terrapin/command_line/runners/posix_runner.rb:39
    def posix_spawn_gem_available?; end
  end
end

# pkg:gem/terrapin#lib/terrapin/command_line/runners/process_runner.rb:5
class Terrapin::CommandLine::ProcessRunner
  # pkg:gem/terrapin#lib/terrapin/command_line/runners/process_runner.rb:18
  def call(command, env = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/process_runner.rb:14
  def supported?; end

  private

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/process_runner.rb:29
  def spawn(*args); end

  # pkg:gem/terrapin#lib/terrapin/command_line/runners/process_runner.rb:33
  def waitpid(pid); end

  class << self
    # pkg:gem/terrapin#lib/terrapin/command_line/runners/process_runner.rb:6
    def available?; end

    # pkg:gem/terrapin#lib/terrapin/command_line/runners/process_runner.rb:10
    def supported?; end
  end
end

# pkg:gem/terrapin#lib/terrapin/exceptions.rb:4
class Terrapin::CommandLineError < ::StandardError; end

# pkg:gem/terrapin#lib/terrapin/exceptions.rb:5
class Terrapin::CommandNotFoundError < ::Terrapin::CommandLineError; end

# pkg:gem/terrapin#lib/terrapin/exceptions.rb:6
class Terrapin::ExitStatusError < ::Terrapin::CommandLineError; end

# pkg:gem/terrapin#lib/terrapin/exceptions.rb:7
class Terrapin::InterpolationError < ::Terrapin::CommandLineError; end

# pkg:gem/terrapin#lib/terrapin/os_detector.rb:26
Terrapin::OS = T.let(T.unsafe(nil), Terrapin::OSDetector)

# pkg:gem/terrapin#lib/terrapin/os_detector.rb:4
class Terrapin::OSDetector
  # pkg:gem/terrapin#lib/terrapin/os_detector.rb:21
  def arch; end

  # pkg:gem/terrapin#lib/terrapin/os_detector.rb:5
  def java?; end

  # pkg:gem/terrapin#lib/terrapin/os_detector.rb:17
  def path_separator; end

  # pkg:gem/terrapin#lib/terrapin/os_detector.rb:9
  def unix?; end

  # pkg:gem/terrapin#lib/terrapin/os_detector.rb:13
  def windows?; end
end
