inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

require:
 - rubocop-sorbet
 - rubocop-rspec

AllCops:
  NewCops: disable
  Exclude:
  - "vendor/**/*"
  - "sorbet/rbi/**/*"
  Include:
  - "sorbet/rbi/shims/**/*.rbi"

RSpec:
  Exclude:
  - 'spec/**/*'

Sorbet:
  Enabled: true

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "**/*.rb"
    - "**/*.rake"

Sorbet/ConstantsFromStrings:
  Enabled: false
