name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linters
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.131.0
        with:
          bundler-cache: true
      - name: Run type check
        run: bundle exec srb tc
      - name: Lint Ruby files
        run: bundle exec rubocop --fail-level error
      - name: Verify documentation
        run: bin/docs
      - name: Run tests
        run: bin/test
      - name: Verify gem RBIs are up-to-date
        run: bin/tapioca gem --verify
      - name: Verify duplicates in shims
        run: bin/tapioca check-shims
